// Code generated by go-swagger; DO NOT EDIT.

package ticket

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"middleman/support/supportclient/models"
)

// NewCloseTicketParams creates a new CloseTicketParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCloseTicketParams() *CloseTicketParams {
	return &CloseTicketParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCloseTicketParamsWithTimeout creates a new CloseTicketParams object
// with the ability to set a timeout on a request.
func NewCloseTicketParamsWithTimeout(timeout time.Duration) *CloseTicketParams {
	return &CloseTicketParams{
		timeout: timeout,
	}
}

// NewCloseTicketParamsWithContext creates a new CloseTicketParams object
// with the ability to set a context for a request.
func NewCloseTicketParamsWithContext(ctx context.Context) *CloseTicketParams {
	return &CloseTicketParams{
		Context: ctx,
	}
}

// NewCloseTicketParamsWithHTTPClient creates a new CloseTicketParams object
// with the ability to set a custom HTTPClient for a request.
func NewCloseTicketParamsWithHTTPClient(client *http.Client) *CloseTicketParams {
	return &CloseTicketParams{
		HTTPClient: client,
	}
}

/*
CloseTicketParams contains all the parameters to send to the API endpoint

	for the close ticket operation.

	Typically these are written to a http.Request.
*/
type CloseTicketParams struct {

	// Body.
	Body *models.SupportServiceCloseTicketBody

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the close ticket params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CloseTicketParams) WithDefaults() *CloseTicketParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the close ticket params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CloseTicketParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the close ticket params
func (o *CloseTicketParams) WithTimeout(timeout time.Duration) *CloseTicketParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the close ticket params
func (o *CloseTicketParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the close ticket params
func (o *CloseTicketParams) WithContext(ctx context.Context) *CloseTicketParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the close ticket params
func (o *CloseTicketParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the close ticket params
func (o *CloseTicketParams) WithHTTPClient(client *http.Client) *CloseTicketParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the close ticket params
func (o *CloseTicketParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the close ticket params
func (o *CloseTicketParams) WithBody(body *models.SupportServiceCloseTicketBody) *CloseTicketParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the close ticket params
func (o *CloseTicketParams) SetBody(body *models.SupportServiceCloseTicketBody) {
	o.Body = body
}

// WithID adds the id to the close ticket params
func (o *CloseTicketParams) WithID(id string) *CloseTicketParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the close ticket params
func (o *CloseTicketParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CloseTicketParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
