// Code generated by go-swagger; DO NOT EDIT.

package ticket

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"middleman/support/supportclient/models"
)

// CreateTicketReader is a Reader for the CreateTicket structure.
type CreateTicketReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateTicketReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateTicketOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCreateTicketDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateTicketOK creates a CreateTicketOK with default headers values
func NewCreateTicketOK() *CreateTicketOK {
	return &CreateTicketOK{}
}

/*
CreateTicketOK describes a response with status code 200, with default header values.

A successful response.
*/
type CreateTicketOK struct {
	Payload *models.SupportpbCreateTicketResponse
}

// IsSuccess returns true when this create ticket o k response has a 2xx status code
func (o *CreateTicketOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create ticket o k response has a 3xx status code
func (o *CreateTicketOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create ticket o k response has a 4xx status code
func (o *CreateTicketOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create ticket o k response has a 5xx status code
func (o *CreateTicketOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create ticket o k response a status code equal to that given
func (o *CreateTicketOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create ticket o k response
func (o *CreateTicketOK) Code() int {
	return 200
}

func (o *CreateTicketOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/support/tickets][%d] createTicketOK %s", 200, payload)
}

func (o *CreateTicketOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/support/tickets][%d] createTicketOK %s", 200, payload)
}

func (o *CreateTicketOK) GetPayload() *models.SupportpbCreateTicketResponse {
	return o.Payload
}

func (o *CreateTicketOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SupportpbCreateTicketResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateTicketDefault creates a CreateTicketDefault with default headers values
func NewCreateTicketDefault(code int) *CreateTicketDefault {
	return &CreateTicketDefault{
		_statusCode: code,
	}
}

/*
CreateTicketDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type CreateTicketDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this create ticket default response has a 2xx status code
func (o *CreateTicketDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this create ticket default response has a 3xx status code
func (o *CreateTicketDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this create ticket default response has a 4xx status code
func (o *CreateTicketDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this create ticket default response has a 5xx status code
func (o *CreateTicketDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this create ticket default response a status code equal to that given
func (o *CreateTicketDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the create ticket default response
func (o *CreateTicketDefault) Code() int {
	return o._statusCode
}

func (o *CreateTicketDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/support/tickets][%d] createTicket default %s", o._statusCode, payload)
}

func (o *CreateTicketDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/support/tickets][%d] createTicket default %s", o._statusCode, payload)
}

func (o *CreateTicketDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *CreateTicketDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
