// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CommentsServiceEditCommentBody comments service edit comment body
//
// swagger:model CommentsServiceEditCommentBody
type CommentsServiceEditCommentBody struct {

	// content
	Content string `json:"content,omitempty"`
}

// Validate validates this comments service edit comment body
func (m *CommentsServiceEditCommentBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this comments service edit comment body based on context it is used
func (m *CommentsServiceEditCommentBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CommentsServiceEditCommentBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CommentsServiceEditCommentBody) UnmarshalBinary(b []byte) error {
	var res CommentsServiceEditCommentBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
