package handlers

import (
	"context"
	"fmt"
	"middleman/internal/am"
	"middleman/internal/ddd"
	"middleman/internal/errorsotel"
	"middleman/internal/registry"
	"middleman/payments/internal/application"
	"middleman/payments/paymentspb"
	"time"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"
)

type commandHandlers struct {
	app application.App
}

func NewCommandHandlers(reg registry.Registry, app application.App, replyPublisher am.ReplyPublisher, mws ...am.MessageHandlerMiddleware) am.MessageHandler {
	return am.NewCommandHandler(reg, replyPublisher, commandHandlers{
		app: app,
	}, mws...)
}

func RegisterCommandHandlers(subscriber am.MessageSubscriber, handlers am.MessageHandler) error {
	_, err := subscriber.Subscribe(paymentspb.CommandChannel, handlers, am.MessageFilter{
		paymentspb.ConfirmPaymentCommand,
		paymentspb.AuthorizePaymentCommand,
	}, am.GroupName("payment-commands"))
	return err
}

func (h commandHandlers) HandleCommand(ctx context.Context, cmd ddd.Command) (reply ddd.Reply, err error) {
	span := trace.SpanFromContext(ctx)
	defer func(started time.Time) {
		if err != nil {
			span.AddEvent(
				"Encountered an error handling command",
				trace.WithAttributes(errorsotel.ErrAttrs(err)...),
			)
		}
		span.AddEvent("Handled command", trace.WithAttributes(
			attribute.Int64("TookMS", time.Since(started).Milliseconds()),
		))
	}(time.Now())

	span.AddEvent("Handling command", trace.WithAttributes(
		attribute.String("Command", cmd.CommandName()),
	))

	switch cmd.CommandName() {
	case paymentspb.AuthorizePaymentCommand:
		return h.doAuthorizePayment(ctx, cmd)
	case paymentspb.ConfirmPaymentCommand:
		return h.doConfirmPayment(ctx, cmd)
	}

	return nil, nil
}

func (h commandHandlers) doAuthorizePayment(ctx context.Context, cmd ddd.Command) (ddd.Reply, error) {
	payload := cmd.Payload().(*paymentspb.AuthorizePaymentRequest)

	// Generate a payment ID (this should ideally come from Stripe or be generated by the domain)
	paymentID := fmt.Sprintf("pi_%d", time.Now().UnixNano())

	// Execute the authorization with the generated payment ID
	err := h.app.AuthorizePayment(ctx, application.AuthorizePaymentCommand{
		PaymentID:      paymentID,
		UserCustomerID: payload.GetUserCustomerId(),
		Amount:         payload.GetAmount(),
		OrderID:        payload.GetOrderId(),
		BasketID:       payload.GetBasketId(),
	})
	if err != nil {
		return nil, err
	}

	// Create a reply with the payment information
	reply := ddd.NewReply(paymentspb.PaymentAuthorizedEvent, &paymentspb.PaymentAuthorized{
		PaymentIntentId: paymentID,
		Amount:          payload.GetAmount(),
		UserCustomerId:  payload.GetUserCustomerId(),
	})

	return reply, nil
}

func (h commandHandlers) doConfirmPayment(ctx context.Context, cmd ddd.Command) (ddd.Reply, error) {
	payload := cmd.Payload().(*paymentspb.ConfirmPayment)

	return nil, h.app.ConfirmPayment(ctx, application.ConfirmPaymentCommand{PaymentID: payload.GetId()})
}
