// Code generated by go-swagger; DO NOT EDIT.

package inventory

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"middleman/erp/erpclient/models"
)

// NewCreateInventoryReservationParams creates a new CreateInventoryReservationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateInventoryReservationParams() *CreateInventoryReservationParams {
	return &CreateInventoryReservationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateInventoryReservationParamsWithTimeout creates a new CreateInventoryReservationParams object
// with the ability to set a timeout on a request.
func NewCreateInventoryReservationParamsWithTimeout(timeout time.Duration) *CreateInventoryReservationParams {
	return &CreateInventoryReservationParams{
		timeout: timeout,
	}
}

// NewCreateInventoryReservationParamsWithContext creates a new CreateInventoryReservationParams object
// with the ability to set a context for a request.
func NewCreateInventoryReservationParamsWithContext(ctx context.Context) *CreateInventoryReservationParams {
	return &CreateInventoryReservationParams{
		Context: ctx,
	}
}

// NewCreateInventoryReservationParamsWithHTTPClient creates a new CreateInventoryReservationParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateInventoryReservationParamsWithHTTPClient(client *http.Client) *CreateInventoryReservationParams {
	return &CreateInventoryReservationParams{
		HTTPClient: client,
	}
}

/*
CreateInventoryReservationParams contains all the parameters to send to the API endpoint

	for the create inventory reservation operation.

	Typically these are written to a http.Request.
*/
type CreateInventoryReservationParams struct {

	// Body.
	Body *models.ErppbCreateInventoryReservationRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create inventory reservation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateInventoryReservationParams) WithDefaults() *CreateInventoryReservationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create inventory reservation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateInventoryReservationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create inventory reservation params
func (o *CreateInventoryReservationParams) WithTimeout(timeout time.Duration) *CreateInventoryReservationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create inventory reservation params
func (o *CreateInventoryReservationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create inventory reservation params
func (o *CreateInventoryReservationParams) WithContext(ctx context.Context) *CreateInventoryReservationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create inventory reservation params
func (o *CreateInventoryReservationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create inventory reservation params
func (o *CreateInventoryReservationParams) WithHTTPClient(client *http.Client) *CreateInventoryReservationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create inventory reservation params
func (o *CreateInventoryReservationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create inventory reservation params
func (o *CreateInventoryReservationParams) WithBody(body *models.ErppbCreateInventoryReservationRequest) *CreateInventoryReservationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create inventory reservation params
func (o *CreateInventoryReservationParams) SetBody(body *models.ErppbCreateInventoryReservationRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateInventoryReservationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
