openapiOptions:
  file:
    - file: "orderingpb/api.proto"
      option:
        info:
          title: Order Processing API
          version: "1.0.0"
          description: "API for managing orders in the system."
        basePath: /
  method:
    # Order Operations
    - method: orderingpb.OrderingService.CreateOrder
      option:
        operationId: createOrder
        tags:
          - Order
        summary: Create a new order


    - method: orderingpb.OrderingService.GetOrder
      option:
        operationId: getOrder
        tags:
          - Order
        summary: Retrieve an order

    - method: orderingpb.OrderingService.CancelOrder
      option:
        operationId: cancelOrder
        tags:
          - Order
        summary: Cancel an order


    - method: orderingpb.OrderingService.ReadyOrder
      option:
        operationId: readyOrder
        tags:
          - Order
        summary: Mark an order as ready


    - method: orderingpb.OrderingService.CompleteOrder
      option:
        operationId: completeOrder
        tags:
          - Order
        summary: Complete an order

