// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"middleman/users/usersclient/models"
)

// WebLoginWithGoogleReader is a Reader for the WebLoginWithGoogle structure.
type WebLoginWithGoogleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WebLoginWithGoogleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWebLoginWithGoogleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewWebLoginWithGoogleDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewWebLoginWithGoogleOK creates a WebLoginWithGoogleOK with default headers values
func NewWebLoginWithGoogleOK() *WebLoginWithGoogleOK {
	return &WebLoginWithGoogleOK{}
}

/*
WebLoginWithGoogleOK describes a response with status code 200, with default header values.

A successful response.
*/
type WebLoginWithGoogleOK struct {
	Payload *models.UserspbLoginUserResponse
}

// IsSuccess returns true when this web login with google o k response has a 2xx status code
func (o *WebLoginWithGoogleOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this web login with google o k response has a 3xx status code
func (o *WebLoginWithGoogleOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this web login with google o k response has a 4xx status code
func (o *WebLoginWithGoogleOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this web login with google o k response has a 5xx status code
func (o *WebLoginWithGoogleOK) IsServerError() bool {
	return false
}

// IsCode returns true when this web login with google o k response a status code equal to that given
func (o *WebLoginWithGoogleOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the web login with google o k response
func (o *WebLoginWithGoogleOK) Code() int {
	return 200
}

func (o *WebLoginWithGoogleOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/users/google-login][%d] webLoginWithGoogleOK %s", 200, payload)
}

func (o *WebLoginWithGoogleOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/users/google-login][%d] webLoginWithGoogleOK %s", 200, payload)
}

func (o *WebLoginWithGoogleOK) GetPayload() *models.UserspbLoginUserResponse {
	return o.Payload
}

func (o *WebLoginWithGoogleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserspbLoginUserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWebLoginWithGoogleDefault creates a WebLoginWithGoogleDefault with default headers values
func NewWebLoginWithGoogleDefault(code int) *WebLoginWithGoogleDefault {
	return &WebLoginWithGoogleDefault{
		_statusCode: code,
	}
}

/*
WebLoginWithGoogleDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type WebLoginWithGoogleDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this web login with google default response has a 2xx status code
func (o *WebLoginWithGoogleDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this web login with google default response has a 3xx status code
func (o *WebLoginWithGoogleDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this web login with google default response has a 4xx status code
func (o *WebLoginWithGoogleDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this web login with google default response has a 5xx status code
func (o *WebLoginWithGoogleDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this web login with google default response a status code equal to that given
func (o *WebLoginWithGoogleDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the web login with google default response
func (o *WebLoginWithGoogleDefault) Code() int {
	return o._statusCode
}

func (o *WebLoginWithGoogleDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/users/google-login][%d] webLoginWithGoogle default %s", o._statusCode, payload)
}

func (o *WebLoginWithGoogleDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/users/google-login][%d] webLoginWithGoogle default %s", o._statusCode, payload)
}

func (o *WebLoginWithGoogleDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *WebLoginWithGoogleDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
