// Code generated by go-swagger; DO NOT EDIT.

package product

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetProductsByCategoryParams creates a new GetProductsByCategoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProductsByCategoryParams() *GetProductsByCategoryParams {
	return &GetProductsByCategoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetProductsByCategoryParamsWithTimeout creates a new GetProductsByCategoryParams object
// with the ability to set a timeout on a request.
func NewGetProductsByCategoryParamsWithTimeout(timeout time.Duration) *GetProductsByCategoryParams {
	return &GetProductsByCategoryParams{
		timeout: timeout,
	}
}

// NewGetProductsByCategoryParamsWithContext creates a new GetProductsByCategoryParams object
// with the ability to set a context for a request.
func NewGetProductsByCategoryParamsWithContext(ctx context.Context) *GetProductsByCategoryParams {
	return &GetProductsByCategoryParams{
		Context: ctx,
	}
}

// NewGetProductsByCategoryParamsWithHTTPClient creates a new GetProductsByCategoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProductsByCategoryParamsWithHTTPClient(client *http.Client) *GetProductsByCategoryParams {
	return &GetProductsByCategoryParams{
		HTTPClient: client,
	}
}

/*
GetProductsByCategoryParams contains all the parameters to send to the API endpoint

	for the get products by category operation.

	Typically these are written to a http.Request.
*/
type GetProductsByCategoryParams struct {

	// CategoryID.
	CategoryID string

	// Page.
	//
	// Format: int64
	Page *string

	// PageSize.
	//
	// Format: int64
	PageSize *string

	// SortBy.
	SortBy *string

	// SortOrder.
	SortOrder *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get products by category params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProductsByCategoryParams) WithDefaults() *GetProductsByCategoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get products by category params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProductsByCategoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get products by category params
func (o *GetProductsByCategoryParams) WithTimeout(timeout time.Duration) *GetProductsByCategoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get products by category params
func (o *GetProductsByCategoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get products by category params
func (o *GetProductsByCategoryParams) WithContext(ctx context.Context) *GetProductsByCategoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get products by category params
func (o *GetProductsByCategoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get products by category params
func (o *GetProductsByCategoryParams) WithHTTPClient(client *http.Client) *GetProductsByCategoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get products by category params
func (o *GetProductsByCategoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCategoryID adds the categoryID to the get products by category params
func (o *GetProductsByCategoryParams) WithCategoryID(categoryID string) *GetProductsByCategoryParams {
	o.SetCategoryID(categoryID)
	return o
}

// SetCategoryID adds the categoryId to the get products by category params
func (o *GetProductsByCategoryParams) SetCategoryID(categoryID string) {
	o.CategoryID = categoryID
}

// WithPage adds the page to the get products by category params
func (o *GetProductsByCategoryParams) WithPage(page *string) *GetProductsByCategoryParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get products by category params
func (o *GetProductsByCategoryParams) SetPage(page *string) {
	o.Page = page
}

// WithPageSize adds the pageSize to the get products by category params
func (o *GetProductsByCategoryParams) WithPageSize(pageSize *string) *GetProductsByCategoryParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the get products by category params
func (o *GetProductsByCategoryParams) SetPageSize(pageSize *string) {
	o.PageSize = pageSize
}

// WithSortBy adds the sortBy to the get products by category params
func (o *GetProductsByCategoryParams) WithSortBy(sortBy *string) *GetProductsByCategoryParams {
	o.SetSortBy(sortBy)
	return o
}

// SetSortBy adds the sortBy to the get products by category params
func (o *GetProductsByCategoryParams) SetSortBy(sortBy *string) {
	o.SortBy = sortBy
}

// WithSortOrder adds the sortOrder to the get products by category params
func (o *GetProductsByCategoryParams) WithSortOrder(sortOrder *string) *GetProductsByCategoryParams {
	o.SetSortOrder(sortOrder)
	return o
}

// SetSortOrder adds the sortOrder to the get products by category params
func (o *GetProductsByCategoryParams) SetSortOrder(sortOrder *string) {
	o.SortOrder = sortOrder
}

// WriteToRequest writes these params to a swagger request
func (o *GetProductsByCategoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param categoryId
	if err := r.SetPathParam("categoryId", o.CategoryID); err != nil {
		return err
	}

	if o.Page != nil {

		// query param page
		var qrPage string

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := qrPage
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.PageSize != nil {

		// query param pageSize
		var qrPageSize string

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := qrPageSize
		if qPageSize != "" {

			if err := r.SetQueryParam("pageSize", qPageSize); err != nil {
				return err
			}
		}
	}

	if o.SortBy != nil {

		// query param sortBy
		var qrSortBy string

		if o.SortBy != nil {
			qrSortBy = *o.SortBy
		}
		qSortBy := qrSortBy
		if qSortBy != "" {

			if err := r.SetQueryParam("sortBy", qSortBy); err != nil {
				return err
			}
		}
	}

	if o.SortOrder != nil {

		// query param sortOrder
		var qrSortOrder string

		if o.SortOrder != nil {
			qrSortOrder = *o.SortOrder
		}
		qSortOrder := qrSortOrder
		if qSortOrder != "" {

			if err := r.SetQueryParam("sortOrder", qSortOrder); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
