// Code generated by mockery v2.53.4. DO NOT EDIT.

package application

import (
	context "context"
	commands "middleman/wishlists/internal/application/commands"

	domain "middleman/wishlists/internal/domain"

	mock "github.com/stretchr/testify/mock"

	queries "middleman/wishlists/internal/application/queries"
)

// MockApp is an autogenerated mock type for the App type
type MockApp struct {
	mock.Mock
}

// AddWishlistItem provides a mock function with given fields: ctx, cmd
func (_m *MockApp) AddWishlistItem(ctx context.Context, cmd commands.AddWishlistItem) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AddWishlistItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AddWishlistItem) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateWishlist provides a mock function with given fields: ctx, cmd
func (_m *MockApp) CreateWishlist(ctx context.Context, cmd commands.CreateWishlist) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CreateWishlist")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CreateWishlist) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetWishlist provides a mock function with given fields: ctx, query
func (_m *MockApp) GetWishlist(ctx context.Context, query queries.GetWishlist) (*domain.MiddlemanWishlist, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetWishlist")
	}

	var r0 *domain.MiddlemanWishlist
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetWishlist) (*domain.MiddlemanWishlist, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetWishlist) *domain.MiddlemanWishlist); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MiddlemanWishlist)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetWishlist) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWishlistItem provides a mock function with given fields: ctx, query
func (_m *MockApp) GetWishlistItem(ctx context.Context, query queries.GetWishlistItem) (*domain.CatalogWishlistItem, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetWishlistItem")
	}

	var r0 *domain.CatalogWishlistItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetWishlistItem) (*domain.CatalogWishlistItem, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetWishlistItem) *domain.CatalogWishlistItem); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CatalogWishlistItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetWishlistItem) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWishlistItems provides a mock function with given fields: ctx, query
func (_m *MockApp) GetWishlistItems(ctx context.Context, query queries.GetWishlistItems) ([]*domain.CatalogWishlistItem, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetWishlistItems")
	}

	var r0 []*domain.CatalogWishlistItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetWishlistItems) ([]*domain.CatalogWishlistItem, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetWishlistItems) []*domain.CatalogWishlistItem); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.CatalogWishlistItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetWishlistItems) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWishlists provides a mock function with given fields: ctx, query
func (_m *MockApp) GetWishlists(ctx context.Context, query queries.GetWishlists) ([]*domain.MiddlemanWishlist, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetWishlists")
	}

	var r0 []*domain.MiddlemanWishlist
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetWishlists) ([]*domain.MiddlemanWishlist, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetWishlists) []*domain.MiddlemanWishlist); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.MiddlemanWishlist)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetWishlists) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveWishlist provides a mock function with given fields: ctx, cmd
func (_m *MockApp) RemoveWishlist(ctx context.Context, cmd commands.RemoveWishlist) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for RemoveWishlist")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.RemoveWishlist) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveWishlistItem provides a mock function with given fields: ctx, cmd
func (_m *MockApp) RemoveWishlistItem(ctx context.Context, cmd commands.RemoveWishlistItem) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for RemoveWishlistItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.RemoveWishlistItem) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockApp creates a new instance of MockApp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApp(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApp {
	mock := &MockApp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
