
apiVersion: v1
kind: Secret
metadata:
  name: common-secrets
  namespace: my-project
type: Opaque
data:
  REDIS_PASSWORD: REDACTED
  JWT_SECRET_KEY: REDACTED
  API_KEY: REDACTED
  STRIPE_KEY: REDACTED
  STRIPE_SECRET: REDACTED
  STRIPE_WEBHOOK_SECRET: REDACTED
  AWS_ACCESS_KEY_ID: REDACTED
  GEOCODING_API_KEY: REDACTED
  NOMINATIM_PASSWORD: REDACTED
  JAEGER_PASSWORD: REDACTED
  GRAFANA_PASSWORD: REDACTED
  PROMETHEUS_PASSWORD: REDACTED
  OTEL_PASSWORD: REDACTED