// Code generated by go-swagger; DO NOT EDIT.

package assistant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new assistant API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new assistant API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new assistant API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for assistant API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	UpdateAssistantConfiguration(params *UpdateAssistantConfigurationParams, opts ...ClientOption) (*UpdateAssistantConfigurationOK, error)

	ActivateAssistant(params *ActivateAssistantParams, opts ...ClientOption) (*ActivateAssistantOK, error)

	DeactivateAssistant(params *DeactivateAssistantParams, opts ...ClientOption) (*DeactivateAssistantOK, error)

	GetAssistant(params *GetAssistantParams, opts ...ClientOption) (*GetAssistantOK, error)

	GetAssistants(params *GetAssistantsParams, opts ...ClientOption) (*GetAssistantsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
UpdateAssistantConfiguration updates assistant configuration
*/
func (a *Client) UpdateAssistantConfiguration(params *UpdateAssistantConfigurationParams, opts ...ClientOption) (*UpdateAssistantConfigurationOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateAssistantConfigurationParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "UpdateAssistantConfiguration",
		Method:             "PUT",
		PathPattern:        "/api/assistants/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &UpdateAssistantConfigurationReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateAssistantConfigurationOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*UpdateAssistantConfigurationDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ActivateAssistant activates a new assistant
*/
func (a *Client) ActivateAssistant(params *ActivateAssistantParams, opts ...ClientOption) (*ActivateAssistantOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewActivateAssistantParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "activateAssistant",
		Method:             "POST",
		PathPattern:        "/api/assistants/{id}/activate",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ActivateAssistantReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ActivateAssistantOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ActivateAssistantDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
DeactivateAssistant deactivates active assistants
*/
func (a *Client) DeactivateAssistant(params *DeactivateAssistantParams, opts ...ClientOption) (*DeactivateAssistantOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeactivateAssistantParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "deactivateAssistant",
		Method:             "POST",
		PathPattern:        "/api/assistants/{id}/deactivate",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeactivateAssistantReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeactivateAssistantOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*DeactivateAssistantDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
GetAssistant retrieves a assistant by ID
*/
func (a *Client) GetAssistant(params *GetAssistantParams, opts ...ClientOption) (*GetAssistantOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAssistantParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getAssistant",
		Method:             "GET",
		PathPattern:        "/api/assistants/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAssistantReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAssistantOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetAssistantDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
GetAssistants retrieves active assistants
*/
func (a *Client) GetAssistants(params *GetAssistantsParams, opts ...ClientOption) (*GetAssistantsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAssistantsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getAssistants",
		Method:             "GET",
		PathPattern:        "/api/assistants",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAssistantsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAssistantsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetAssistantsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
