// Code generated by mockery v2.53.4. DO NOT EDIT.

package application

import (
	context "context"
	commands "middleman/activity/internal/application/commands"

	mock "github.com/stretchr/testify/mock"
)

// MockCommands is an autogenerated mock type for the Commands type
type MockCommands struct {
	mock.Mock
}

// AddInteraction provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) AddInteraction(ctx context.Context, cmd commands.AddInteraction) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AddInteraction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AddInteraction) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateActivity provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) CreateActivity(ctx context.Context, cmd commands.CreateActivity) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CreateActivity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CreateActivity) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveInteraction provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) RemoveInteraction(ctx context.Context, cmd commands.RemoveInteraction) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for RemoveInteraction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.RemoveInteraction) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateInteraction provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) UpdateInteraction(ctx context.Context, cmd commands.UpdateInteraction) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInteraction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.UpdateInteraction) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockCommands creates a new instance of MockCommands. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommands(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommands {
	mock := &MockCommands{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
