// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OfferspbEndLeaseResponse offerspb end lease response
//
// swagger:model offerspbEndLeaseResponse
type OfferspbEndLeaseResponse struct {

	// ended at
	// Format: date-time
	EndedAt strfmt.DateTime `json:"endedAt,omitempty"`

	// lease Id
	LeaseID string `json:"leaseId,omitempty"`

	// lease status
	LeaseStatus string `json:"leaseStatus,omitempty"`
}

// Validate validates this offerspb end lease response
func (m *OfferspbEndLeaseResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEndedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OfferspbEndLeaseResponse) validateEndedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.EndedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("endedAt", "body", "date-time", m.EndedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this offerspb end lease response based on context it is used
func (m *OfferspbEndLeaseResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OfferspbEndLeaseResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OfferspbEndLeaseResponse) UnmarshalBinary(b []byte) error {
	var res OfferspbEndLeaseResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
