// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OfferspbOffer offerspb offer
//
// swagger:model offerspbOffer
type OfferspbOffer struct {

	// id
	ID string `json:"id,omitempty"`

	// e.g. "draft", "active", "accepted", "closed", ""
	OfferStatus string `json:"offerStatus,omitempty"`

	// Potential initial price
	Price string `json:"price,omitempty"`

	// Product being offered
	ProductID string `json:"productId,omitempty"`

	// ID of the buyer (once accepted)
	UserCustomerID string `json:"userCustomerId,omitempty"`

	// ID of the seller
	UserSellerID string `json:"userSellerId,omitempty"`
}

// Validate validates this offerspb offer
func (m *OfferspbOffer) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this offerspb offer based on context it is used
func (m *OfferspbOffer) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OfferspbOffer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OfferspbOffer) UnmarshalBinary(b []byte) error {
	var res OfferspbOffer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
