// Code generated by go-swagger; DO NOT EDIT.

package sync

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"middleman/erp/erpclient/models"
)

// SyncPricesReader is a Reader for the SyncPrices structure.
type SyncPricesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SyncPricesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSyncPricesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSyncPricesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSyncPricesOK creates a SyncPricesOK with default headers values
func NewSyncPricesOK() *SyncPricesOK {
	return &SyncPricesOK{}
}

/*
SyncPricesOK describes a response with status code 200, with default header values.

A successful response.
*/
type SyncPricesOK struct {
	Payload *models.ErppbSyncPricesResponse
}

// IsSuccess returns true when this sync prices o k response has a 2xx status code
func (o *SyncPricesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this sync prices o k response has a 3xx status code
func (o *SyncPricesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this sync prices o k response has a 4xx status code
func (o *SyncPricesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this sync prices o k response has a 5xx status code
func (o *SyncPricesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this sync prices o k response a status code equal to that given
func (o *SyncPricesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the sync prices o k response
func (o *SyncPricesOK) Code() int {
	return 200
}

func (o *SyncPricesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/erp/connectors/{connectorId}/sync/prices][%d] syncPricesOK %s", 200, payload)
}

func (o *SyncPricesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/erp/connectors/{connectorId}/sync/prices][%d] syncPricesOK %s", 200, payload)
}

func (o *SyncPricesOK) GetPayload() *models.ErppbSyncPricesResponse {
	return o.Payload
}

func (o *SyncPricesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErppbSyncPricesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSyncPricesDefault creates a SyncPricesDefault with default headers values
func NewSyncPricesDefault(code int) *SyncPricesDefault {
	return &SyncPricesDefault{
		_statusCode: code,
	}
}

/*
SyncPricesDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type SyncPricesDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this sync prices default response has a 2xx status code
func (o *SyncPricesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this sync prices default response has a 3xx status code
func (o *SyncPricesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this sync prices default response has a 4xx status code
func (o *SyncPricesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this sync prices default response has a 5xx status code
func (o *SyncPricesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this sync prices default response a status code equal to that given
func (o *SyncPricesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the sync prices default response
func (o *SyncPricesDefault) Code() int {
	return o._statusCode
}

func (o *SyncPricesDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/erp/connectors/{connectorId}/sync/prices][%d] syncPrices default %s", o._statusCode, payload)
}

func (o *SyncPricesDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/erp/connectors/{connectorId}/sync/prices][%d] syncPrices default %s", o._statusCode, payload)
}

func (o *SyncPricesDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *SyncPricesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
