// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: reviewspb/api.proto

package reviewspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReviewsService_AddReview_FullMethodName                 = "/reviewspb.ReviewsService/AddReview"
	ReviewsService_ApproveReview_FullMethodName             = "/reviewspb.ReviewsService/ApproveReview"
	ReviewsService_RejectReview_FullMethodName              = "/reviewspb.ReviewsService/RejectReview"
	ReviewsService_FlagReview_FullMethodName                = "/reviewspb.ReviewsService/FlagReview"
	ReviewsService_EditReview_FullMethodName                = "/reviewspb.ReviewsService/EditReview"
	ReviewsService_RemoveReview_FullMethodName              = "/reviewspb.ReviewsService/RemoveReview"
	ReviewsService_GetReview_FullMethodName                 = "/reviewspb.ReviewsService/GetReview"
	ReviewsService_GetReviews_FullMethodName                = "/reviewspb.ReviewsService/GetReviews"
	ReviewsService_GetMostReviewed_FullMethodName           = "/reviewspb.ReviewsService/GetMostReviewed"
	ReviewsService_GetMostReviewedByCategory_FullMethodName = "/reviewspb.ReviewsService/GetMostReviewedByCategory"
	ReviewsService_GetReviewsBySender_FullMethodName        = "/reviewspb.ReviewsService/GetReviewsBySender"
	ReviewsService_GetApprovedReviews_FullMethodName        = "/reviewspb.ReviewsService/GetApprovedReviews"
)

// ReviewsServiceClient is the client API for ReviewsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ReviewsService provides functionalities related to review and reply management.
type ReviewsServiceClient interface {
	// Adds a new review.
	AddReview(ctx context.Context, in *AddReviewRequest, opts ...grpc.CallOption) (*AddReviewResponse, error)
	ApproveReview(ctx context.Context, in *ApproveReviewRequest, opts ...grpc.CallOption) (*ApproveReviewResponse, error)
	RejectReview(ctx context.Context, in *RejectReviewRequest, opts ...grpc.CallOption) (*RejectReviewResponse, error)
	FlagReview(ctx context.Context, in *FlagReviewRequest, opts ...grpc.CallOption) (*FlagReviewResponse, error)
	EditReview(ctx context.Context, in *EditReviewRequest, opts ...grpc.CallOption) (*EditReviewResponse, error)
	RemoveReview(ctx context.Context, in *RemoveReviewRequest, opts ...grpc.CallOption) (*RemoveReviewResponse, error)
	GetReview(ctx context.Context, in *GetReviewRequest, opts ...grpc.CallOption) (*GetReviewResponse, error)
	GetReviews(ctx context.Context, in *GetReviewsRequest, opts ...grpc.CallOption) (*GetReviewsResponse, error)
	GetMostReviewed(ctx context.Context, in *GetMostReviewedRequest, opts ...grpc.CallOption) (*GetMostReviewedResponse, error)
	GetMostReviewedByCategory(ctx context.Context, in *GetMostReviewedByCategoryRequest, opts ...grpc.CallOption) (*GetMostReviewedByCategoryResponse, error)
	GetReviewsBySender(ctx context.Context, in *GetReviewsBySenderRequest, opts ...grpc.CallOption) (*GetReviewsBySenderResponse, error)
	GetApprovedReviews(ctx context.Context, in *GetApprovedReviewsRequest, opts ...grpc.CallOption) (*GetApprovedReviewsResponse, error)
}

type reviewsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReviewsServiceClient(cc grpc.ClientConnInterface) ReviewsServiceClient {
	return &reviewsServiceClient{cc}
}

func (c *reviewsServiceClient) AddReview(ctx context.Context, in *AddReviewRequest, opts ...grpc.CallOption) (*AddReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddReviewResponse)
	err := c.cc.Invoke(ctx, ReviewsService_AddReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewsServiceClient) ApproveReview(ctx context.Context, in *ApproveReviewRequest, opts ...grpc.CallOption) (*ApproveReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveReviewResponse)
	err := c.cc.Invoke(ctx, ReviewsService_ApproveReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewsServiceClient) RejectReview(ctx context.Context, in *RejectReviewRequest, opts ...grpc.CallOption) (*RejectReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectReviewResponse)
	err := c.cc.Invoke(ctx, ReviewsService_RejectReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewsServiceClient) FlagReview(ctx context.Context, in *FlagReviewRequest, opts ...grpc.CallOption) (*FlagReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlagReviewResponse)
	err := c.cc.Invoke(ctx, ReviewsService_FlagReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewsServiceClient) EditReview(ctx context.Context, in *EditReviewRequest, opts ...grpc.CallOption) (*EditReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditReviewResponse)
	err := c.cc.Invoke(ctx, ReviewsService_EditReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewsServiceClient) RemoveReview(ctx context.Context, in *RemoveReviewRequest, opts ...grpc.CallOption) (*RemoveReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveReviewResponse)
	err := c.cc.Invoke(ctx, ReviewsService_RemoveReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewsServiceClient) GetReview(ctx context.Context, in *GetReviewRequest, opts ...grpc.CallOption) (*GetReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReviewResponse)
	err := c.cc.Invoke(ctx, ReviewsService_GetReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewsServiceClient) GetReviews(ctx context.Context, in *GetReviewsRequest, opts ...grpc.CallOption) (*GetReviewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReviewsResponse)
	err := c.cc.Invoke(ctx, ReviewsService_GetReviews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewsServiceClient) GetMostReviewed(ctx context.Context, in *GetMostReviewedRequest, opts ...grpc.CallOption) (*GetMostReviewedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMostReviewedResponse)
	err := c.cc.Invoke(ctx, ReviewsService_GetMostReviewed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewsServiceClient) GetMostReviewedByCategory(ctx context.Context, in *GetMostReviewedByCategoryRequest, opts ...grpc.CallOption) (*GetMostReviewedByCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMostReviewedByCategoryResponse)
	err := c.cc.Invoke(ctx, ReviewsService_GetMostReviewedByCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewsServiceClient) GetReviewsBySender(ctx context.Context, in *GetReviewsBySenderRequest, opts ...grpc.CallOption) (*GetReviewsBySenderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReviewsBySenderResponse)
	err := c.cc.Invoke(ctx, ReviewsService_GetReviewsBySender_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewsServiceClient) GetApprovedReviews(ctx context.Context, in *GetApprovedReviewsRequest, opts ...grpc.CallOption) (*GetApprovedReviewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetApprovedReviewsResponse)
	err := c.cc.Invoke(ctx, ReviewsService_GetApprovedReviews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReviewsServiceServer is the server API for ReviewsService service.
// All implementations must embed UnimplementedReviewsServiceServer
// for forward compatibility.
//
// ReviewsService provides functionalities related to review and reply management.
type ReviewsServiceServer interface {
	// Adds a new review.
	AddReview(context.Context, *AddReviewRequest) (*AddReviewResponse, error)
	ApproveReview(context.Context, *ApproveReviewRequest) (*ApproveReviewResponse, error)
	RejectReview(context.Context, *RejectReviewRequest) (*RejectReviewResponse, error)
	FlagReview(context.Context, *FlagReviewRequest) (*FlagReviewResponse, error)
	EditReview(context.Context, *EditReviewRequest) (*EditReviewResponse, error)
	RemoveReview(context.Context, *RemoveReviewRequest) (*RemoveReviewResponse, error)
	GetReview(context.Context, *GetReviewRequest) (*GetReviewResponse, error)
	GetReviews(context.Context, *GetReviewsRequest) (*GetReviewsResponse, error)
	GetMostReviewed(context.Context, *GetMostReviewedRequest) (*GetMostReviewedResponse, error)
	GetMostReviewedByCategory(context.Context, *GetMostReviewedByCategoryRequest) (*GetMostReviewedByCategoryResponse, error)
	GetReviewsBySender(context.Context, *GetReviewsBySenderRequest) (*GetReviewsBySenderResponse, error)
	GetApprovedReviews(context.Context, *GetApprovedReviewsRequest) (*GetApprovedReviewsResponse, error)
	mustEmbedUnimplementedReviewsServiceServer()
}

// UnimplementedReviewsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReviewsServiceServer struct{}

func (UnimplementedReviewsServiceServer) AddReview(context.Context, *AddReviewRequest) (*AddReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddReview not implemented")
}
func (UnimplementedReviewsServiceServer) ApproveReview(context.Context, *ApproveReviewRequest) (*ApproveReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveReview not implemented")
}
func (UnimplementedReviewsServiceServer) RejectReview(context.Context, *RejectReviewRequest) (*RejectReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectReview not implemented")
}
func (UnimplementedReviewsServiceServer) FlagReview(context.Context, *FlagReviewRequest) (*FlagReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlagReview not implemented")
}
func (UnimplementedReviewsServiceServer) EditReview(context.Context, *EditReviewRequest) (*EditReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditReview not implemented")
}
func (UnimplementedReviewsServiceServer) RemoveReview(context.Context, *RemoveReviewRequest) (*RemoveReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveReview not implemented")
}
func (UnimplementedReviewsServiceServer) GetReview(context.Context, *GetReviewRequest) (*GetReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReview not implemented")
}
func (UnimplementedReviewsServiceServer) GetReviews(context.Context, *GetReviewsRequest) (*GetReviewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReviews not implemented")
}
func (UnimplementedReviewsServiceServer) GetMostReviewed(context.Context, *GetMostReviewedRequest) (*GetMostReviewedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMostReviewed not implemented")
}
func (UnimplementedReviewsServiceServer) GetMostReviewedByCategory(context.Context, *GetMostReviewedByCategoryRequest) (*GetMostReviewedByCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMostReviewedByCategory not implemented")
}
func (UnimplementedReviewsServiceServer) GetReviewsBySender(context.Context, *GetReviewsBySenderRequest) (*GetReviewsBySenderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReviewsBySender not implemented")
}
func (UnimplementedReviewsServiceServer) GetApprovedReviews(context.Context, *GetApprovedReviewsRequest) (*GetApprovedReviewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApprovedReviews not implemented")
}
func (UnimplementedReviewsServiceServer) mustEmbedUnimplementedReviewsServiceServer() {}
func (UnimplementedReviewsServiceServer) testEmbeddedByValue()                        {}

// UnsafeReviewsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReviewsServiceServer will
// result in compilation errors.
type UnsafeReviewsServiceServer interface {
	mustEmbedUnimplementedReviewsServiceServer()
}

func RegisterReviewsServiceServer(s grpc.ServiceRegistrar, srv ReviewsServiceServer) {
	// If the following call pancis, it indicates UnimplementedReviewsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReviewsService_ServiceDesc, srv)
}

func _ReviewsService_AddReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewsServiceServer).AddReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewsService_AddReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewsServiceServer).AddReview(ctx, req.(*AddReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewsService_ApproveReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewsServiceServer).ApproveReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewsService_ApproveReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewsServiceServer).ApproveReview(ctx, req.(*ApproveReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewsService_RejectReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewsServiceServer).RejectReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewsService_RejectReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewsServiceServer).RejectReview(ctx, req.(*RejectReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewsService_FlagReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlagReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewsServiceServer).FlagReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewsService_FlagReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewsServiceServer).FlagReview(ctx, req.(*FlagReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewsService_EditReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewsServiceServer).EditReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewsService_EditReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewsServiceServer).EditReview(ctx, req.(*EditReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewsService_RemoveReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewsServiceServer).RemoveReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewsService_RemoveReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewsServiceServer).RemoveReview(ctx, req.(*RemoveReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewsService_GetReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewsServiceServer).GetReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewsService_GetReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewsServiceServer).GetReview(ctx, req.(*GetReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewsService_GetReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewsServiceServer).GetReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewsService_GetReviews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewsServiceServer).GetReviews(ctx, req.(*GetReviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewsService_GetMostReviewed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMostReviewedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewsServiceServer).GetMostReviewed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewsService_GetMostReviewed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewsServiceServer).GetMostReviewed(ctx, req.(*GetMostReviewedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewsService_GetMostReviewedByCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMostReviewedByCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewsServiceServer).GetMostReviewedByCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewsService_GetMostReviewedByCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewsServiceServer).GetMostReviewedByCategory(ctx, req.(*GetMostReviewedByCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewsService_GetReviewsBySender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReviewsBySenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewsServiceServer).GetReviewsBySender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewsService_GetReviewsBySender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewsServiceServer).GetReviewsBySender(ctx, req.(*GetReviewsBySenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewsService_GetApprovedReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApprovedReviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewsServiceServer).GetApprovedReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewsService_GetApprovedReviews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewsServiceServer).GetApprovedReviews(ctx, req.(*GetApprovedReviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReviewsService_ServiceDesc is the grpc.ServiceDesc for ReviewsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReviewsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reviewspb.ReviewsService",
	HandlerType: (*ReviewsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddReview",
			Handler:    _ReviewsService_AddReview_Handler,
		},
		{
			MethodName: "ApproveReview",
			Handler:    _ReviewsService_ApproveReview_Handler,
		},
		{
			MethodName: "RejectReview",
			Handler:    _ReviewsService_RejectReview_Handler,
		},
		{
			MethodName: "FlagReview",
			Handler:    _ReviewsService_FlagReview_Handler,
		},
		{
			MethodName: "EditReview",
			Handler:    _ReviewsService_EditReview_Handler,
		},
		{
			MethodName: "RemoveReview",
			Handler:    _ReviewsService_RemoveReview_Handler,
		},
		{
			MethodName: "GetReview",
			Handler:    _ReviewsService_GetReview_Handler,
		},
		{
			MethodName: "GetReviews",
			Handler:    _ReviewsService_GetReviews_Handler,
		},
		{
			MethodName: "GetMostReviewed",
			Handler:    _ReviewsService_GetMostReviewed_Handler,
		},
		{
			MethodName: "GetMostReviewedByCategory",
			Handler:    _ReviewsService_GetMostReviewedByCategory_Handler,
		},
		{
			MethodName: "GetReviewsBySender",
			Handler:    _ReviewsService_GetReviewsBySender_Handler,
		},
		{
			MethodName: "GetApprovedReviews",
			Handler:    _ReviewsService_GetApprovedReviews_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reviewspb/api.proto",
}
