// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: reviewspb/events.proto

package reviewspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Command
type AddReview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemType      string                 `protobuf:"bytes,4,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CategoryId    string                 `protobuf:"bytes,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,7,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReview) Reset() {
	*x = AddReview{}
	mi := &file_reviewspb_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReview) ProtoMessage() {}

func (x *AddReview) ProtoReflect() protoreflect.Message {
	mi := &file_reviewspb_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReview.ProtoReflect.Descriptor instead.
func (*AddReview) Descriptor() ([]byte, []int) {
	return file_reviewspb_events_proto_rawDescGZIP(), []int{0}
}

func (x *AddReview) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddReview) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *AddReview) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *AddReview) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *AddReview) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddReview) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *AddReview) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type ReviewAdded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemType      string                 `protobuf:"bytes,4,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CategoryId    string                 `protobuf:"bytes,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,7,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewAdded) Reset() {
	*x = ReviewAdded{}
	mi := &file_reviewspb_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewAdded) ProtoMessage() {}

func (x *ReviewAdded) ProtoReflect() protoreflect.Message {
	mi := &file_reviewspb_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewAdded.ProtoReflect.Descriptor instead.
func (*ReviewAdded) Descriptor() ([]byte, []int) {
	return file_reviewspb_events_proto_rawDescGZIP(), []int{1}
}

func (x *ReviewAdded) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReviewAdded) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ReviewAdded) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ReviewAdded) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *ReviewAdded) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReviewAdded) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *ReviewAdded) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type ReviewApproved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Approve       bool                   `protobuf:"varint,2,opt,name=approve,proto3" json:"approve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewApproved) Reset() {
	*x = ReviewApproved{}
	mi := &file_reviewspb_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewApproved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewApproved) ProtoMessage() {}

func (x *ReviewApproved) ProtoReflect() protoreflect.Message {
	mi := &file_reviewspb_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewApproved.ProtoReflect.Descriptor instead.
func (*ReviewApproved) Descriptor() ([]byte, []int) {
	return file_reviewspb_events_proto_rawDescGZIP(), []int{2}
}

func (x *ReviewApproved) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReviewApproved) GetApprove() bool {
	if x != nil {
		return x.Approve
	}
	return false
}

type ReviewRemoved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewRemoved) Reset() {
	*x = ReviewRemoved{}
	mi := &file_reviewspb_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewRemoved) ProtoMessage() {}

func (x *ReviewRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_reviewspb_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewRemoved.ProtoReflect.Descriptor instead.
func (*ReviewRemoved) Descriptor() ([]byte, []int) {
	return file_reviewspb_events_proto_rawDescGZIP(), []int{3}
}

func (x *ReviewRemoved) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReviewFlagged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Flagged       bool                   `protobuf:"varint,2,opt,name=flagged,proto3" json:"flagged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewFlagged) Reset() {
	*x = ReviewFlagged{}
	mi := &file_reviewspb_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewFlagged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewFlagged) ProtoMessage() {}

func (x *ReviewFlagged) ProtoReflect() protoreflect.Message {
	mi := &file_reviewspb_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewFlagged.ProtoReflect.Descriptor instead.
func (*ReviewFlagged) Descriptor() ([]byte, []int) {
	return file_reviewspb_events_proto_rawDescGZIP(), []int{4}
}

func (x *ReviewFlagged) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReviewFlagged) GetFlagged() bool {
	if x != nil {
		return x.Flagged
	}
	return false
}

type ReviewRejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Approved      bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewRejected) Reset() {
	*x = ReviewRejected{}
	mi := &file_reviewspb_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewRejected) ProtoMessage() {}

func (x *ReviewRejected) ProtoReflect() protoreflect.Message {
	mi := &file_reviewspb_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewRejected.ProtoReflect.Descriptor instead.
func (*ReviewRejected) Descriptor() ([]byte, []int) {
	return file_reviewspb_events_proto_rawDescGZIP(), []int{5}
}

func (x *ReviewRejected) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReviewRejected) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

type ReviewEdited struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewEdited) Reset() {
	*x = ReviewEdited{}
	mi := &file_reviewspb_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewEdited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewEdited) ProtoMessage() {}

func (x *ReviewEdited) ProtoReflect() protoreflect.Message {
	mi := &file_reviewspb_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewEdited.ProtoReflect.Descriptor instead.
func (*ReviewEdited) Descriptor() ([]byte, []int) {
	return file_reviewspb_events_proto_rawDescGZIP(), []int{6}
}

func (x *ReviewEdited) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReviewEdited) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_reviewspb_events_proto protoreflect.FileDescriptor

const file_reviewspb_events_proto_rawDesc = "" +
	"\n" +
	"\x16reviewspb/events.proto\x12\treviewspb\"\xc6\x01\n" +
	"\tAddReview\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\tR\x06itemId\x12\x1b\n" +
	"\titem_type\x18\x04 \x01(\tR\bitemType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1f\n" +
	"\vcategory_id\x18\x06 \x01(\tR\n" +
	"categoryId\x12\x1b\n" +
	"\tparent_id\x18\a \x01(\tR\bparentId\"\xc8\x01\n" +
	"\vReviewAdded\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\tR\x06itemId\x12\x1b\n" +
	"\titem_type\x18\x04 \x01(\tR\bitemType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1f\n" +
	"\vcategory_id\x18\x06 \x01(\tR\n" +
	"categoryId\x12\x1b\n" +
	"\tparent_id\x18\a \x01(\tR\bparentId\":\n" +
	"\x0eReviewApproved\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aapprove\x18\x02 \x01(\bR\aapprove\"\x1f\n" +
	"\rReviewRemoved\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\rReviewFlagged\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aflagged\x18\x02 \x01(\bR\aflagged\"<\n" +
	"\x0eReviewRejected\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\"8\n" +
	"\fReviewEdited\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontentB\x87\x01\n" +
	"\rcom.reviewspbB\vEventsProtoP\x01Z%middleman/reviews/reviewspb/reviewspb\xa2\x02\x03RXX\xaa\x02\tReviewspb\xca\x02\tReviewspb\xe2\x02\x15Reviewspb\\GPBMetadata\xea\x02\tReviewspbb\x06proto3"

var (
	file_reviewspb_events_proto_rawDescOnce sync.Once
	file_reviewspb_events_proto_rawDescData []byte
)

func file_reviewspb_events_proto_rawDescGZIP() []byte {
	file_reviewspb_events_proto_rawDescOnce.Do(func() {
		file_reviewspb_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reviewspb_events_proto_rawDesc), len(file_reviewspb_events_proto_rawDesc)))
	})
	return file_reviewspb_events_proto_rawDescData
}

var file_reviewspb_events_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_reviewspb_events_proto_goTypes = []any{
	(*AddReview)(nil),      // 0: reviewspb.AddReview
	(*ReviewAdded)(nil),    // 1: reviewspb.ReviewAdded
	(*ReviewApproved)(nil), // 2: reviewspb.ReviewApproved
	(*ReviewRemoved)(nil),  // 3: reviewspb.ReviewRemoved
	(*ReviewFlagged)(nil),  // 4: reviewspb.ReviewFlagged
	(*ReviewRejected)(nil), // 5: reviewspb.ReviewRejected
	(*ReviewEdited)(nil),   // 6: reviewspb.ReviewEdited
}
var file_reviewspb_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_reviewspb_events_proto_init() }
func file_reviewspb_events_proto_init() {
	if File_reviewspb_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reviewspb_events_proto_rawDesc), len(file_reviewspb_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reviewspb_events_proto_goTypes,
		DependencyIndexes: file_reviewspb_events_proto_depIdxs,
		MessageInfos:      file_reviewspb_events_proto_msgTypes,
	}.Build()
	File_reviewspb_events_proto = out.File
	file_reviewspb_events_proto_goTypes = nil
	file_reviewspb_events_proto_depIdxs = nil
}
