package constants

// ServiceName The name of this module/service
const ServiceName = "assistants"

// GRPC Service Names
const (
	AssistantsServiceName = "ASSISTANTS"
	ProductsServiceName   = "PRODUCTS"

	PostsServiceName         = "POSTS"
	ServicesServiceName      = "SERVICES"
	CommentsServiceName      = "COMMENTS"
	ActivityServiceName      = "ACTIVITY"
	MessagesServiceName      = "MESSAGES"
	FollowingServiceName     = "FOLLOWING"
	ReviewsServiceName       = "REVIEWS"
	SearchServiceName        = "SEARCH"
	UserServiceName          = "USERS"
	CategoriesServiceName    = "CATEGORIES"
	MediaServiceName         = "MEDIA"
	NewsServiceName          = "NEWSLETTERS"
	WishlistsServiceName     = "WISHLISTS"
	SupportsServiceName      = "SUPPORT"
	MetricsServiceName       = "METRICS"
	ShippingServiceName      = "SHIPPING"
	PaymentsServiceName      = "PAYMENTS"
	OrderingServiceName      = "ORDERING"
	OffersServiceName        = "OFFERS"
	NotificationsServiceName = "NOTIFICATIONS"
	MailerServiceName        = "MAILER"
	GeocodingServiceName     = "GEOCODING"
	BasketsServiceName       = "BASKETS"
	ErpServiceName           = "ERP"
)

// Dependency Injection Keys
const (
	RegistryKey                        = "registry"
	DomainDispatcherKey                = "domainDispatcher"
	DatabaseTransactionKey             = "tx"
	MessagePublisherKey                = "messagePublisher"
	MessageSubscriberKey               = "messageSubscriber"
	EventPublisherKey                  = "eventPublisher"
	InboxStoreKey                      = "inboxStore"
	AggregateStoreKey                  = "aggregateStore"
	AssistantsRepoKey                  = "assistantsRepo"
	ConversationsRepoKey               = "conversationsRepo"
	AssistantJournalRepoKey            = "assistantJournalRepo"
	ApplicationKey                     = "app"
	DomainEventHandlersKey             = "domainEventHandlers"
	ReadConversationHandlersKey        = "readConversationHandlers"
	AssistantCatalogHandlersKey        = "assistantCatalogHandlers"
	ReadMessagesHandlersKey            = "readMessagesHandlers"
	AssistantServiceKey                = "assistantService"
	ProductRepositoryKey               = "productRepository"
	PostRepositoryKey                  = "postRepository"
	ActivityRepositoryKey              = "activityRepository"
	UserRepositoryKey                  = "userRepository"
	DealRepositoryKey                  = "dealRepository"
	JobRepositoryKey                   = "jobRepository"
	PropertyRepositoryKey              = "propertyRepository"
	VehicleRepositoryKey               = "vehicleRepository"
	ServiceRepositoryKey               = "serviceRepository"
	WishlistRepositoryKey              = "wishlistRepository"
	ReviewRepositoryKey                = "reviewRepository"
	FollowingRepositoryKey             = "followingRepository"
	CommentRepositoryKey               = "commentRepository"
	MessagesRepositoryKey              = "messagesRepository"
	ReadConversationRepositoryKey      = "readConversationRepository"
	ReadMessagesRepositoryKey          = "readMessagesRepository"
	VariantRepositoryKey               = "variantRepository"
	MetricRepositoryKey                = "metricRepository"
	SupportRepositoryKey               = "supportRepository"
	ShippingRepositoryKey              = "shippingRepository"
	PaymentRepositoryKey               = "paymentRepository"
	OrderRepositoryKey                 = "orderRepository"
	OfferRepositoryKey                 = "offerRepository"
	NotificationRepositoryKey          = "notificationRepository"
	NewsletterRepositoryKey            = "newsletterRepository"
	MediaRepositoryKey                 = "mediaRepository"
	MailerRepositoryKey                = "mailerRepository"
	CategoryRepositoryKey              = "categoryRepository"
	SpeechProcessorKey                 = "speechProcessor"
	VisionProcessorKey                 = "visionProcessor"
	DocumentProcessorKey               = "documentProcessor"
	DataProcessorKey                   = "dataProcessor"
	GeocodingRepositoryKey             = "geocodingRepository"
	BasketRepositoryKey                = "basketRepository"
	VectorRepositoryKey                = "vectorRepository"
	IntegrationEventHandlersKey        = "integrationEventHandlers"
	AnalysisTypeAnalyzeStructure       = "analyze_structure"
	AnalysisTypeSummarize              = "summarize"
	AnalysisTypeClassify               = "classify"
	AIClientProvider                   = "ai_client_provider"
	AIModelSelector                    = "ai_model_selector"
	SecurityValidator                  = "security_validator"
	LLMProcessor                       = "llm_processor"
	LLMPromptSystem                    = "llm-prompt-system"
	ProductionToolRegistry             = "production_tool_registry"
	ProductionToolRegistryWithAuth     = "production_tool_registry_with_auth"
	EnhancedLLMProcessor               = "enhanced_llm_processor"
	UnifiedRepositoryInterface         = "unified_repository_interface"
	UnifiedRepositoryInterfaceWithAuth = "unified_repository_interface_with_auth"
	RepositoryLanguageProcessor        = "repository_language_processor"
	StreamingToolExecutor              = "streaming_tool_executor"
	StreamingToolExecutorWithAuth      = "streaming_tool_executor_with_auth"
	CatalogRepositoryKey               = "catalogRepository"
	SystemPromptProvider               = "system_prompt_provider"
	AnthropicClient                    = "anthropic-client"
	OpenAIClient                       = "openai-client"
	DeepSeekAiClient                   = "deepseek-client"
	GoogleAiClient                     = "google-client"
	OutboxTableName                    = ServiceName + ".outbox"
	InboxTableName                     = ServiceName + ".inbox"
	EventsTableName                    = ServiceName + ".events"
	SnapshotsTableName                 = ServiceName + ".snapshots"
	SagasTableName                     = ServiceName + ".sagas"
	CatalogTableName                   = ServiceName + ".assistants"
	ReadConversationTableName          = ServiceName + ".conversations"
	ReadMessagesTableName              = ServiceName + ".conversation_messages"
	ServiceConfigKey                   = "ServiceConfig"
	RepositoryFactoryKey               = "RepositoryFactory"
)

// Direct Database Repository Keys (Performance Critical)
const (
	PerformanceOptimizer        = "performance_optimizer"
	AIRepositoryLanguageService = "ai_repository_language_service"
	UnifiedSchemaService        = "unified_schema_service"
)
