// Code generated by go-swagger; DO NOT EDIT.

package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"middleman/media/mediaclient/models"
)

// GetAllItemImagesReader is a Reader for the GetAllItemImages structure.
type GetAllItemImagesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllItemImagesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllItemImagesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetAllItemImagesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAllItemImagesOK creates a GetAllItemImagesOK with default headers values
func NewGetAllItemImagesOK() *GetAllItemImagesOK {
	return &GetAllItemImagesOK{}
}

/*
GetAllItemImagesOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetAllItemImagesOK struct {
	Payload *models.MediapbGetAllItemImagesResponse
}

// IsSuccess returns true when this get all item images o k response has a 2xx status code
func (o *GetAllItemImagesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get all item images o k response has a 3xx status code
func (o *GetAllItemImagesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get all item images o k response has a 4xx status code
func (o *GetAllItemImagesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get all item images o k response has a 5xx status code
func (o *GetAllItemImagesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get all item images o k response a status code equal to that given
func (o *GetAllItemImagesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get all item images o k response
func (o *GetAllItemImagesOK) Code() int {
	return 200
}

func (o *GetAllItemImagesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/media/item/{itemId}/image][%d] getAllItemImagesOK %s", 200, payload)
}

func (o *GetAllItemImagesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/media/item/{itemId}/image][%d] getAllItemImagesOK %s", 200, payload)
}

func (o *GetAllItemImagesOK) GetPayload() *models.MediapbGetAllItemImagesResponse {
	return o.Payload
}

func (o *GetAllItemImagesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MediapbGetAllItemImagesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllItemImagesDefault creates a GetAllItemImagesDefault with default headers values
func NewGetAllItemImagesDefault(code int) *GetAllItemImagesDefault {
	return &GetAllItemImagesDefault{
		_statusCode: code,
	}
}

/*
GetAllItemImagesDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetAllItemImagesDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this get all item images default response has a 2xx status code
func (o *GetAllItemImagesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get all item images default response has a 3xx status code
func (o *GetAllItemImagesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get all item images default response has a 4xx status code
func (o *GetAllItemImagesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get all item images default response has a 5xx status code
func (o *GetAllItemImagesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get all item images default response a status code equal to that given
func (o *GetAllItemImagesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get all item images default response
func (o *GetAllItemImagesDefault) Code() int {
	return o._statusCode
}

func (o *GetAllItemImagesDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/media/item/{itemId}/image][%d] getAllItemImages default %s", o._statusCode, payload)
}

func (o *GetAllItemImagesDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/media/item/{itemId}/image][%d] getAllItemImages default %s", o._statusCode, payload)
}

func (o *GetAllItemImagesDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *GetAllItemImagesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
