// Code generated by go-swagger; DO NOT EDIT.

package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"middleman/media/mediaclient/models"
)

// GetAllImagesByAuthorReader is a Reader for the GetAllImagesByAuthor structure.
type GetAllImagesByAuthorReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllImagesByAuthorReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllImagesByAuthorOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetAllImagesByAuthorDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAllImagesByAuthorOK creates a GetAllImagesByAuthorOK with default headers values
func NewGetAllImagesByAuthorOK() *GetAllImagesByAuthorOK {
	return &GetAllImagesByAuthorOK{}
}

/*
GetAllImagesByAuthorOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetAllImagesByAuthorOK struct {
	Payload *models.MediapbGetAllImagesByAuthorResponse
}

// IsSuccess returns true when this get all images by author o k response has a 2xx status code
func (o *GetAllImagesByAuthorOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get all images by author o k response has a 3xx status code
func (o *GetAllImagesByAuthorOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get all images by author o k response has a 4xx status code
func (o *GetAllImagesByAuthorOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get all images by author o k response has a 5xx status code
func (o *GetAllImagesByAuthorOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get all images by author o k response a status code equal to that given
func (o *GetAllImagesByAuthorOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get all images by author o k response
func (o *GetAllImagesByAuthorOK) Code() int {
	return 200
}

func (o *GetAllImagesByAuthorOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/media/image/author/{userId}][%d] getAllImagesByAuthorOK %s", 200, payload)
}

func (o *GetAllImagesByAuthorOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/media/image/author/{userId}][%d] getAllImagesByAuthorOK %s", 200, payload)
}

func (o *GetAllImagesByAuthorOK) GetPayload() *models.MediapbGetAllImagesByAuthorResponse {
	return o.Payload
}

func (o *GetAllImagesByAuthorOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MediapbGetAllImagesByAuthorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllImagesByAuthorDefault creates a GetAllImagesByAuthorDefault with default headers values
func NewGetAllImagesByAuthorDefault(code int) *GetAllImagesByAuthorDefault {
	return &GetAllImagesByAuthorDefault{
		_statusCode: code,
	}
}

/*
GetAllImagesByAuthorDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetAllImagesByAuthorDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this get all images by author default response has a 2xx status code
func (o *GetAllImagesByAuthorDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get all images by author default response has a 3xx status code
func (o *GetAllImagesByAuthorDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get all images by author default response has a 4xx status code
func (o *GetAllImagesByAuthorDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get all images by author default response has a 5xx status code
func (o *GetAllImagesByAuthorDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get all images by author default response a status code equal to that given
func (o *GetAllImagesByAuthorDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get all images by author default response
func (o *GetAllImagesByAuthorDefault) Code() int {
	return o._statusCode
}

func (o *GetAllImagesByAuthorDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/media/image/author/{userId}][%d] getAllImagesByAuthor default %s", o._statusCode, payload)
}

func (o *GetAllImagesByAuthorDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/media/image/author/{userId}][%d] getAllImagesByAuthor default %s", o._statusCode, payload)
}

func (o *GetAllImagesByAuthorDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *GetAllImagesByAuthorDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
