// Code generated by go-swagger; DO NOT EDIT.

package support

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"middleman/support/supportclient/models"
)

// StartSupportReader is a Reader for the StartSupport structure.
type StartSupportReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StartSupportReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStartSupportOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewStartSupportDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewStartSupportOK creates a StartSupportOK with default headers values
func NewStartSupportOK() *StartSupportOK {
	return &StartSupportOK{}
}

/*
StartSupportOK describes a response with status code 200, with default header values.

A successful response.
*/
type StartSupportOK struct {
	Payload *models.SupportpbStartSupportResponse
}

// IsSuccess returns true when this start support o k response has a 2xx status code
func (o *StartSupportOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this start support o k response has a 3xx status code
func (o *StartSupportOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this start support o k response has a 4xx status code
func (o *StartSupportOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this start support o k response has a 5xx status code
func (o *StartSupportOK) IsServerError() bool {
	return false
}

// IsCode returns true when this start support o k response a status code equal to that given
func (o *StartSupportOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the start support o k response
func (o *StartSupportOK) Code() int {
	return 200
}

func (o *StartSupportOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/support][%d] startSupportOK %s", 200, payload)
}

func (o *StartSupportOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/support][%d] startSupportOK %s", 200, payload)
}

func (o *StartSupportOK) GetPayload() *models.SupportpbStartSupportResponse {
	return o.Payload
}

func (o *StartSupportOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SupportpbStartSupportResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStartSupportDefault creates a StartSupportDefault with default headers values
func NewStartSupportDefault(code int) *StartSupportDefault {
	return &StartSupportDefault{
		_statusCode: code,
	}
}

/*
StartSupportDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type StartSupportDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this start support default response has a 2xx status code
func (o *StartSupportDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this start support default response has a 3xx status code
func (o *StartSupportDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this start support default response has a 4xx status code
func (o *StartSupportDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this start support default response has a 5xx status code
func (o *StartSupportDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this start support default response a status code equal to that given
func (o *StartSupportDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the start support default response
func (o *StartSupportDefault) Code() int {
	return o._statusCode
}

func (o *StartSupportDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/support][%d] startSupport default %s", o._statusCode, payload)
}

func (o *StartSupportDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/support][%d] startSupport default %s", o._statusCode, payload)
}

func (o *StartSupportDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *StartSupportDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
