// Code generated by mockery v2.53.4. DO NOT EDIT.

package application

import (
	context "context"
	domain "middleman/posts/internal/domain"

	mock "github.com/stretchr/testify/mock"

	queries "middleman/posts/internal/application/queries"
)

// MockQueries is an autogenerated mock type for the Queries type
type MockQueries struct {
	mock.Mock
}

// GetPost provides a mock function with given fields: ctx, query
func (_m *MockQueries) GetPost(ctx context.Context, query queries.GetPost) (*domain.CatalogPost, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetPost")
	}

	var r0 *domain.CatalogPost
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetPost) (*domain.CatalogPost, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetPost) *domain.CatalogPost); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CatalogPost)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetPost) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPosts provides a mock function with given fields: ctx, query
func (_m *MockQueries) GetPosts(ctx context.Context, query queries.GetPosts) ([]*domain.CatalogPost, int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetPosts")
	}

	var r0 []*domain.CatalogPost
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetPosts) ([]*domain.CatalogPost, int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetPosts) []*domain.CatalogPost); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.CatalogPost)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetPosts) int64); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, queries.GetPosts) error); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetPostsByCategory provides a mock function with given fields: ctx, query
func (_m *MockQueries) GetPostsByCategory(ctx context.Context, query queries.GetPostsByCategory) ([]*domain.CatalogPost, int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetPostsByCategory")
	}

	var r0 []*domain.CatalogPost
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetPostsByCategory) ([]*domain.CatalogPost, int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetPostsByCategory) []*domain.CatalogPost); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.CatalogPost)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetPostsByCategory) int64); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, queries.GetPostsByCategory) error); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetPostsByCategorySlug provides a mock function with given fields: ctx, query
func (_m *MockQueries) GetPostsByCategorySlug(ctx context.Context, query queries.GetPostsByCategorySlug) ([]*domain.CatalogPost, int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetPostsByCategorySlug")
	}

	var r0 []*domain.CatalogPost
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetPostsByCategorySlug) ([]*domain.CatalogPost, int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetPostsByCategorySlug) []*domain.CatalogPost); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.CatalogPost)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetPostsByCategorySlug) int64); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, queries.GetPostsByCategorySlug) error); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetPostsWithFilters provides a mock function with given fields: ctx, query
func (_m *MockQueries) GetPostsWithFilters(ctx context.Context, query queries.GetPostsWithFilters) ([]*domain.CatalogPost, int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetPostsWithFilters")
	}

	var r0 []*domain.CatalogPost
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetPostsWithFilters) ([]*domain.CatalogPost, int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetPostsWithFilters) []*domain.CatalogPost); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.CatalogPost)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetPostsWithFilters) int64); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, queries.GetPostsWithFilters) error); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetPublicCatalog provides a mock function with given fields: ctx, query
func (_m *MockQueries) GetPublicCatalog(ctx context.Context, query queries.GetPublicCatalog) ([]*domain.CatalogPost, int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicCatalog")
	}

	var r0 []*domain.CatalogPost
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetPublicCatalog) ([]*domain.CatalogPost, int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetPublicCatalog) []*domain.CatalogPost); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.CatalogPost)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetPublicCatalog) int64); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, queries.GetPublicCatalog) error); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetUserPosts provides a mock function with given fields: ctx, query
func (_m *MockQueries) GetUserPosts(ctx context.Context, query queries.GetUserPosts) ([]*domain.CatalogPost, int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPosts")
	}

	var r0 []*domain.CatalogPost
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetUserPosts) ([]*domain.CatalogPost, int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetUserPosts) []*domain.CatalogPost); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.CatalogPost)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetUserPosts) int64); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, queries.GetUserPosts) error); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewMockQueries creates a new instance of MockQueries. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueries(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueries {
	mock := &MockQueries{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
