// Code generated by go-swagger; DO NOT EDIT.

package support_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"middleman/support/supportclient/models"
)

// SupportServiceListTicketsReader is a Reader for the SupportServiceListTickets structure.
type SupportServiceListTicketsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SupportServiceListTicketsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSupportServiceListTicketsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSupportServiceListTicketsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSupportServiceListTicketsOK creates a SupportServiceListTicketsOK with default headers values
func NewSupportServiceListTicketsOK() *SupportServiceListTicketsOK {
	return &SupportServiceListTicketsOK{}
}

/*
SupportServiceListTicketsOK describes a response with status code 200, with default header values.

A successful response.
*/
type SupportServiceListTicketsOK struct {
	Payload *models.SupportpbListTicketsResponse
}

// IsSuccess returns true when this support service list tickets o k response has a 2xx status code
func (o *SupportServiceListTicketsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this support service list tickets o k response has a 3xx status code
func (o *SupportServiceListTicketsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this support service list tickets o k response has a 4xx status code
func (o *SupportServiceListTicketsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this support service list tickets o k response has a 5xx status code
func (o *SupportServiceListTicketsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this support service list tickets o k response a status code equal to that given
func (o *SupportServiceListTicketsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the support service list tickets o k response
func (o *SupportServiceListTicketsOK) Code() int {
	return 200
}

func (o *SupportServiceListTicketsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/support/tickets][%d] supportServiceListTicketsOK %s", 200, payload)
}

func (o *SupportServiceListTicketsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/support/tickets][%d] supportServiceListTicketsOK %s", 200, payload)
}

func (o *SupportServiceListTicketsOK) GetPayload() *models.SupportpbListTicketsResponse {
	return o.Payload
}

func (o *SupportServiceListTicketsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SupportpbListTicketsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSupportServiceListTicketsDefault creates a SupportServiceListTicketsDefault with default headers values
func NewSupportServiceListTicketsDefault(code int) *SupportServiceListTicketsDefault {
	return &SupportServiceListTicketsDefault{
		_statusCode: code,
	}
}

/*
SupportServiceListTicketsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type SupportServiceListTicketsDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this support service list tickets default response has a 2xx status code
func (o *SupportServiceListTicketsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this support service list tickets default response has a 3xx status code
func (o *SupportServiceListTicketsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this support service list tickets default response has a 4xx status code
func (o *SupportServiceListTicketsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this support service list tickets default response has a 5xx status code
func (o *SupportServiceListTicketsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this support service list tickets default response a status code equal to that given
func (o *SupportServiceListTicketsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the support service list tickets default response
func (o *SupportServiceListTicketsDefault) Code() int {
	return o._statusCode
}

func (o *SupportServiceListTicketsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/support/tickets][%d] SupportService_ListTickets default %s", o._statusCode, payload)
}

func (o *SupportServiceListTicketsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/support/tickets][%d] SupportService_ListTickets default %s", o._statusCode, payload)
}

func (o *SupportServiceListTicketsDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *SupportServiceListTicketsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
