// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ErppbSendOrderResponse erppb send order response
//
// swagger:model erppbSendOrderResponse
type ErppbSendOrderResponse struct {

	// external Id
	ExternalID string `json:"externalId,omitempty"`

	// order Id
	OrderID string `json:"orderId,omitempty"`

	// result
	Result interface{} `json:"result,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this erppb send order response
func (m *ErppbSendOrderResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this erppb send order response based on context it is used
func (m *ErppbSendOrderResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ErppbSendOrderResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ErppbSendOrderResponse) UnmarshalBinary(b []byte) error {
	var res ErppbSendOrderResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
