// Code generated by mockery v2.53.4. DO NOT EDIT.

package application

import (
	context "context"
	commands "middleman/notifications/internal/application/commands"

	domain "middleman/notifications/internal/domain"

	mock "github.com/stretchr/testify/mock"

	queries "middleman/notifications/internal/application/queries"
)

// MockApp is an autogenerated mock type for the App type
type MockApp struct {
	mock.Mock
}

// AddBasketAlert provides a mock function with given fields: ctx, cmd
func (_m *MockApp) AddBasketAlert(ctx context.Context, cmd commands.AddBasketAlert) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AddBasketAlert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AddBasketAlert) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddCommentAlert provides a mock function with given fields: ctx, cmd
func (_m *MockApp) AddCommentAlert(ctx context.Context, cmd commands.AddCommentAlert) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AddCommentAlert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AddCommentAlert) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddFollowingAlert provides a mock function with given fields: ctx, cmd
func (_m *MockApp) AddFollowingAlert(ctx context.Context, cmd commands.AddFollowingAlert) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AddFollowingAlert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AddFollowingAlert) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddInteractionAlert provides a mock function with given fields: ctx, cmd
func (_m *MockApp) AddInteractionAlert(ctx context.Context, cmd commands.AddInteractionAlert) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AddInteractionAlert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AddInteractionAlert) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddMessageAlert provides a mock function with given fields: ctx, cmd
func (_m *MockApp) AddMessageAlert(ctx context.Context, cmd commands.AddMessageAlert) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AddMessageAlert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AddMessageAlert) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddOfferAlert provides a mock function with given fields: ctx, cmd
func (_m *MockApp) AddOfferAlert(ctx context.Context, cmd commands.AddOfferAlert) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AddOfferAlert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AddOfferAlert) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddOrderAlert provides a mock function with given fields: ctx, cmd
func (_m *MockApp) AddOrderAlert(ctx context.Context, cmd commands.AddOrderAlert) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AddOrderAlert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AddOrderAlert) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddPaymentAlert provides a mock function with given fields: ctx, cmd
func (_m *MockApp) AddPaymentAlert(ctx context.Context, cmd commands.AddPaymentAlert) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AddPaymentAlert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AddPaymentAlert) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddProductAlert provides a mock function with given fields: ctx, cmd
func (_m *MockApp) AddProductAlert(ctx context.Context, cmd commands.AddProductAlert) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AddProductAlert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AddProductAlert) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddReviewAlert provides a mock function with given fields: ctx, cmd
func (_m *MockApp) AddReviewAlert(ctx context.Context, cmd commands.AddReviewAlert) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AddReviewAlert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AddReviewAlert) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddSupportAlert provides a mock function with given fields: ctx, cmd
func (_m *MockApp) AddSupportAlert(ctx context.Context, cmd commands.AddSupportAlert) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AddSupportAlert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AddSupportAlert) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddWishlistAlert provides a mock function with given fields: ctx, cmd
func (_m *MockApp) AddWishlistAlert(ctx context.Context, cmd commands.AddWishlistAlert) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AddWishlistAlert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AddWishlistAlert) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAlert provides a mock function with given fields: ctx, cmd
func (_m *MockApp) DeleteAlert(ctx context.Context, cmd commands.DeleteAlert) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAlert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.DeleteAlert) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAlertsByType provides a mock function with given fields: ctx, query
func (_m *MockApp) GetAlertsByType(ctx context.Context, query queries.GetAlertsByType) ([]*domain.MiddlemanAlert, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetAlertsByType")
	}

	var r0 []*domain.MiddlemanAlert
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetAlertsByType) ([]*domain.MiddlemanAlert, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetAlertsByType) []*domain.MiddlemanAlert); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.MiddlemanAlert)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetAlertsByType) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPreferences provides a mock function with given fields: ctx, query
func (_m *MockApp) GetPreferences(ctx context.Context, query queries.GetPreferences) (*domain.UserPreferences, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetPreferences")
	}

	var r0 *domain.UserPreferences
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetPreferences) (*domain.UserPreferences, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetPreferences) *domain.UserPreferences); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserPreferences)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetPreferences) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAlerts provides a mock function with given fields: ctx, query
func (_m *MockApp) ListAlerts(ctx context.Context, query queries.ListAlerts) ([]*domain.MiddlemanAlert, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for ListAlerts")
	}

	var r0 []*domain.MiddlemanAlert
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.ListAlerts) ([]*domain.MiddlemanAlert, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.ListAlerts) []*domain.MiddlemanAlert); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.MiddlemanAlert)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.ListAlerts) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadAlert provides a mock function with given fields: ctx, cmd
func (_m *MockApp) ReadAlert(ctx context.Context, cmd commands.ReadAlert) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for ReadAlert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.ReadAlert) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePreferences provides a mock function with given fields: ctx, cmd
func (_m *MockApp) UpdatePreferences(ctx context.Context, cmd commands.UpdatePreferences) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePreferences")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.UpdatePreferences) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockApp creates a new instance of MockApp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApp(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApp {
	mock := &MockApp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
