// Code generated by go-swagger; DO NOT EDIT.

package action

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"middleman/scheduler/schedulerclient/models"
)

// NewAddActionParams creates a new AddActionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddActionParams() *AddActionParams {
	return &AddActionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddActionParamsWithTimeout creates a new AddActionParams object
// with the ability to set a timeout on a request.
func NewAddActionParamsWithTimeout(timeout time.Duration) *AddActionParams {
	return &AddActionParams{
		timeout: timeout,
	}
}

// NewAddActionParamsWithContext creates a new AddActionParams object
// with the ability to set a context for a request.
func NewAddActionParamsWithContext(ctx context.Context) *AddActionParams {
	return &AddActionParams{
		Context: ctx,
	}
}

// NewAddActionParamsWithHTTPClient creates a new AddActionParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddActionParamsWithHTTPClient(client *http.Client) *AddActionParams {
	return &AddActionParams{
		HTTPClient: client,
	}
}

/*
AddActionParams contains all the parameters to send to the API endpoint

	for the add action operation.

	Typically these are written to a http.Request.
*/
type AddActionParams struct {

	/* Body.

	   Request message to add a new scheduled action.
	*/
	Body *models.SchedulerspbAddActionRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add action params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddActionParams) WithDefaults() *AddActionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add action params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddActionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add action params
func (o *AddActionParams) WithTimeout(timeout time.Duration) *AddActionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add action params
func (o *AddActionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add action params
func (o *AddActionParams) WithContext(ctx context.Context) *AddActionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add action params
func (o *AddActionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add action params
func (o *AddActionParams) WithHTTPClient(client *http.Client) *AddActionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add action params
func (o *AddActionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add action params
func (o *AddActionParams) WithBody(body *models.SchedulerspbAddActionRequest) *AddActionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add action params
func (o *AddActionParams) SetBody(body *models.SchedulerspbAddActionRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AddActionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
