// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewslettersServiceUpdateNewsletterBody newsletters service update newsletter body
//
// swagger:model NewslettersServiceUpdateNewsletterBody
type NewslettersServiceUpdateNewsletterBody struct {

	// category
	Category string `json:"category,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// frequency
	Frequency string `json:"frequency,omitempty"`

	// is active
	IsActive bool `json:"isActive,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// template Id
	TemplateID string `json:"templateId,omitempty"`
}

// Validate validates this newsletters service update newsletter body
func (m *NewslettersServiceUpdateNewsletterBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newsletters service update newsletter body based on context it is used
func (m *NewslettersServiceUpdateNewsletterBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewslettersServiceUpdateNewsletterBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewslettersServiceUpdateNewsletterBody) UnmarshalBinary(b []byte) error {
	var res NewslettersServiceUpdateNewsletterBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
