// Code generated by go-swagger; DO NOT EDIT.

package communication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new communication API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new communication API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new communication API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for communication API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	AddInternalNote(params *AddInternalNoteParams, opts ...ClientOption) (*AddInternalNoteOK, error)

	AddTicketReply(params *AddTicketReplyParams, opts ...ClientOption) (*AddTicketReplyOK, error)

	GetTicketCommunications(params *GetTicketCommunicationsParams, opts ...ClientOption) (*GetTicketCommunicationsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
AddInternalNote adds an internal note to a ticket
*/
func (a *Client) AddInternalNote(params *AddInternalNoteParams, opts ...ClientOption) (*AddInternalNoteOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAddInternalNoteParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "addInternalNote",
		Method:             "POST",
		PathPattern:        "/api/support/tickets/{ticketId}/notes",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &AddInternalNoteReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AddInternalNoteOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*AddInternalNoteDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
AddTicketReply adds a reply to a ticket
*/
func (a *Client) AddTicketReply(params *AddTicketReplyParams, opts ...ClientOption) (*AddTicketReplyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAddTicketReplyParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "addTicketReply",
		Method:             "POST",
		PathPattern:        "/api/support/tickets/{ticketId}/replies",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &AddTicketReplyReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AddTicketReplyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*AddTicketReplyDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
GetTicketCommunications gets all communications for a ticket
*/
func (a *Client) GetTicketCommunications(params *GetTicketCommunicationsParams, opts ...ClientOption) (*GetTicketCommunicationsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetTicketCommunicationsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getTicketCommunications",
		Method:             "GET",
		PathPattern:        "/api/support/tickets/{ticketId}/communications",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetTicketCommunicationsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetTicketCommunicationsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetTicketCommunicationsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
