// Code generated by go-swagger; DO NOT EDIT.

package review

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"middleman/reviews/reviewsclient/models"
)

// RejectReviewReader is a Reader for the RejectReview structure.
type RejectReviewReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RejectReviewReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRejectReviewOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRejectReviewDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRejectReviewOK creates a RejectReviewOK with default headers values
func NewRejectReviewOK() *RejectReviewOK {
	return &RejectReviewOK{}
}

/*
RejectReviewOK describes a response with status code 200, with default header values.

A successful response.
*/
type RejectReviewOK struct {
	Payload *models.ReviewspbRejectReviewResponse
}

// IsSuccess returns true when this reject review o k response has a 2xx status code
func (o *RejectReviewOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this reject review o k response has a 3xx status code
func (o *RejectReviewOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this reject review o k response has a 4xx status code
func (o *RejectReviewOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this reject review o k response has a 5xx status code
func (o *RejectReviewOK) IsServerError() bool {
	return false
}

// IsCode returns true when this reject review o k response a status code equal to that given
func (o *RejectReviewOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the reject review o k response
func (o *RejectReviewOK) Code() int {
	return 200
}

func (o *RejectReviewOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/reviews/{id}/reject][%d] rejectReviewOK %s", 200, payload)
}

func (o *RejectReviewOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/reviews/{id}/reject][%d] rejectReviewOK %s", 200, payload)
}

func (o *RejectReviewOK) GetPayload() *models.ReviewspbRejectReviewResponse {
	return o.Payload
}

func (o *RejectReviewOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ReviewspbRejectReviewResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRejectReviewDefault creates a RejectReviewDefault with default headers values
func NewRejectReviewDefault(code int) *RejectReviewDefault {
	return &RejectReviewDefault{
		_statusCode: code,
	}
}

/*
RejectReviewDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RejectReviewDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this reject review default response has a 2xx status code
func (o *RejectReviewDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this reject review default response has a 3xx status code
func (o *RejectReviewDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this reject review default response has a 4xx status code
func (o *RejectReviewDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this reject review default response has a 5xx status code
func (o *RejectReviewDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this reject review default response a status code equal to that given
func (o *RejectReviewDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the reject review default response
func (o *RejectReviewDefault) Code() int {
	return o._statusCode
}

func (o *RejectReviewDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/reviews/{id}/reject][%d] rejectReview default %s", o._statusCode, payload)
}

func (o *RejectReviewDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/reviews/{id}/reject][%d] rejectReview default %s", o._statusCode, payload)
}

func (o *RejectReviewDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *RejectReviewDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
