// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ReviewspbEditReviewResponse reviewspb edit review response
//
// swagger:model reviewspbEditReviewResponse
type ReviewspbEditReviewResponse struct {

	// content
	Content string `json:"content,omitempty"`

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this reviewspb edit review response
func (m *ReviewspbEditReviewResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this reviewspb edit review response based on context it is used
func (m *ReviewspbEditReviewResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ReviewspbEditReviewResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReviewspbEditReviewResponse) UnmarshalBinary(b []byte) error {
	var res ReviewspbEditReviewResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
