// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: managerspb/events.proto

package managerspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event when manager is authorized
type ManagerAuthorized struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerAuthorized) Reset() {
	*x = ManagerAuthorized{}
	mi := &file_managerspb_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerAuthorized) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerAuthorized) ProtoMessage() {}

func (x *ManagerAuthorized) ProtoReflect() protoreflect.Message {
	mi := &file_managerspb_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerAuthorized.ProtoReflect.Descriptor instead.
func (*ManagerAuthorized) Descriptor() ([]byte, []int) {
	return file_managerspb_events_proto_rawDescGZIP(), []int{0}
}

func (x *ManagerAuthorized) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Event when a new manager is created
type ManagerCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Capabilities  []ManagerCapability    `protobuf:"varint,6,rep,packed,name=capabilities,proto3,enum=managerspb.ManagerCapability" json:"capabilities,omitempty"`
	Temperature   float64                `protobuf:"fixed64,7,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,8,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,9,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	UserId        string                 `protobuf:"bytes,10,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerCreated) Reset() {
	*x = ManagerCreated{}
	mi := &file_managerspb_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerCreated) ProtoMessage() {}

func (x *ManagerCreated) ProtoReflect() protoreflect.Message {
	mi := &file_managerspb_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerCreated.ProtoReflect.Descriptor instead.
func (*ManagerCreated) Descriptor() ([]byte, []int) {
	return file_managerspb_events_proto_rawDescGZIP(), []int{1}
}

func (x *ManagerCreated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ManagerCreated) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ManagerCreated) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ManagerCreated) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ManagerCreated) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ManagerCreated) GetCapabilities() []ManagerCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ManagerCreated) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ManagerCreated) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ManagerCreated) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *ManagerCreated) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Event when an manager is activated
type ManagerActivated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`               // Manager ID (UUID)
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // When the activation occurred
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerActivated) Reset() {
	*x = ManagerActivated{}
	mi := &file_managerspb_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerActivated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerActivated) ProtoMessage() {}

func (x *ManagerActivated) ProtoReflect() protoreflect.Message {
	mi := &file_managerspb_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerActivated.ProtoReflect.Descriptor instead.
func (*ManagerActivated) Descriptor() ([]byte, []int) {
	return file_managerspb_events_proto_rawDescGZIP(), []int{2}
}

func (x *ManagerActivated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ManagerActivated) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// Event when an manager is deactivated
type ManagerDeactivated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`               // Manager ID (UUID)
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // When the deactivation occurred
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerDeactivated) Reset() {
	*x = ManagerDeactivated{}
	mi := &file_managerspb_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerDeactivated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerDeactivated) ProtoMessage() {}

func (x *ManagerDeactivated) ProtoReflect() protoreflect.Message {
	mi := &file_managerspb_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerDeactivated.ProtoReflect.Descriptor instead.
func (*ManagerDeactivated) Descriptor() ([]byte, []int) {
	return file_managerspb_events_proto_rawDescGZIP(), []int{3}
}

func (x *ManagerDeactivated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ManagerDeactivated) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// Event when an manager's configuration is updated
type ManagerConfigurationUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                         // Manager ID (UUID)
	Temperature   float64                `protobuf:"fixed64,2,opt,name=temperature,proto3" json:"temperature,omitempty"`                     // Updated temperature setting
	MaxTokens     int32                  `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`         // Updated max tokens setting
	SystemPrompt  string                 `protobuf:"bytes,4,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"` // Updated system prompt
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`          // When the update occurred
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerConfigurationUpdated) Reset() {
	*x = ManagerConfigurationUpdated{}
	mi := &file_managerspb_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerConfigurationUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerConfigurationUpdated) ProtoMessage() {}

func (x *ManagerConfigurationUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_managerspb_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerConfigurationUpdated.ProtoReflect.Descriptor instead.
func (*ManagerConfigurationUpdated) Descriptor() ([]byte, []int) {
	return file_managerspb_events_proto_rawDescGZIP(), []int{4}
}

func (x *ManagerConfigurationUpdated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ManagerConfigurationUpdated) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ManagerConfigurationUpdated) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ManagerConfigurationUpdated) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *ManagerConfigurationUpdated) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Event when an manager processes a user request
type ManagerRequestProcessed struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                                                   // Manager ID (UUID)
	RequestId       string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                                                                                    // Request ID
	UserId          string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                                                             // User ID who made the request
	Message         string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                                                                                                         // User's request message
	Context         map[string]string      `protobuf:"bytes,5,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`                               // Request context
	RequestType     string                 `protobuf:"bytes,6,opt,name=request_type,json=requestType,proto3" json:"request_type,omitempty"`                                                                              // Type of request
	ResponseId      string                 `protobuf:"bytes,7,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`                                                                                 // Response ID
	ResponseMessage string                 `protobuf:"bytes,8,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`                                                                  // Manager's response
	ResponseData    map[string]string      `protobuf:"bytes,9,rep,name=response_data,json=responseData,proto3" json:"response_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Response data
	Actions         []*ManagerAction       `protobuf:"bytes,10,rep,name=actions,proto3" json:"actions,omitempty"`                                                                                                        // Actions performed
	Timestamp       string                 `protobuf:"bytes,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                                                    // When processing completed
	Status          string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`                                                                                                          // Processing status
	Confidence      float64                `protobuf:"fixed64,13,opt,name=confidence,proto3" json:"confidence,omitempty"`                                                                                                // Confidence score
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ManagerRequestProcessed) Reset() {
	*x = ManagerRequestProcessed{}
	mi := &file_managerspb_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerRequestProcessed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerRequestProcessed) ProtoMessage() {}

func (x *ManagerRequestProcessed) ProtoReflect() protoreflect.Message {
	mi := &file_managerspb_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerRequestProcessed.ProtoReflect.Descriptor instead.
func (*ManagerRequestProcessed) Descriptor() ([]byte, []int) {
	return file_managerspb_events_proto_rawDescGZIP(), []int{5}
}

func (x *ManagerRequestProcessed) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ManagerRequestProcessed) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ManagerRequestProcessed) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ManagerRequestProcessed) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ManagerRequestProcessed) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ManagerRequestProcessed) GetRequestType() string {
	if x != nil {
		return x.RequestType
	}
	return ""
}

func (x *ManagerRequestProcessed) GetResponseId() string {
	if x != nil {
		return x.ResponseId
	}
	return ""
}

func (x *ManagerRequestProcessed) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

func (x *ManagerRequestProcessed) GetResponseData() map[string]string {
	if x != nil {
		return x.ResponseData
	}
	return nil
}

func (x *ManagerRequestProcessed) GetActions() []*ManagerAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *ManagerRequestProcessed) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ManagerRequestProcessed) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ManagerRequestProcessed) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

// Event when a manager logs in
type ManagerLoggedIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Manager ID (UUID)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerLoggedIn) Reset() {
	*x = ManagerLoggedIn{}
	mi := &file_managerspb_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerLoggedIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerLoggedIn) ProtoMessage() {}

func (x *ManagerLoggedIn) ProtoReflect() protoreflect.Message {
	mi := &file_managerspb_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerLoggedIn.ProtoReflect.Descriptor instead.
func (*ManagerLoggedIn) Descriptor() ([]byte, []int) {
	return file_managerspb_events_proto_rawDescGZIP(), []int{6}
}

func (x *ManagerLoggedIn) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Event when a manager logs out
type ManagerLoggedOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Manager ID (UUID)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerLoggedOut) Reset() {
	*x = ManagerLoggedOut{}
	mi := &file_managerspb_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerLoggedOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerLoggedOut) ProtoMessage() {}

func (x *ManagerLoggedOut) ProtoReflect() protoreflect.Message {
	mi := &file_managerspb_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerLoggedOut.ProtoReflect.Descriptor instead.
func (*ManagerLoggedOut) Descriptor() ([]byte, []int) {
	return file_managerspb_events_proto_rawDescGZIP(), []int{7}
}

func (x *ManagerLoggedOut) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Event when a manager's participation in a service or activity is toggled
type ManagerParticipationToggled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                        // Manager ID (UUID)
	Participating bool                   `protobuf:"varint,2,opt,name=participating,proto3" json:"participating,omitempty"` // True if participating, False if not
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerParticipationToggled) Reset() {
	*x = ManagerParticipationToggled{}
	mi := &file_managerspb_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerParticipationToggled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerParticipationToggled) ProtoMessage() {}

func (x *ManagerParticipationToggled) ProtoReflect() protoreflect.Message {
	mi := &file_managerspb_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerParticipationToggled.ProtoReflect.Descriptor instead.
func (*ManagerParticipationToggled) Descriptor() ([]byte, []int) {
	return file_managerspb_events_proto_rawDescGZIP(), []int{8}
}

func (x *ManagerParticipationToggled) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ManagerParticipationToggled) GetParticipating() bool {
	if x != nil {
		return x.Participating
	}
	return false
}

// Event when a manager changes their name
type ManagerRenamed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // Manager ID (UUID)
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // The updated name of the manager (renamed for clarity)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerRenamed) Reset() {
	*x = ManagerRenamed{}
	mi := &file_managerspb_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerRenamed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerRenamed) ProtoMessage() {}

func (x *ManagerRenamed) ProtoReflect() protoreflect.Message {
	mi := &file_managerspb_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerRenamed.ProtoReflect.Descriptor instead.
func (*ManagerRenamed) Descriptor() ([]byte, []int) {
	return file_managerspb_events_proto_rawDescGZIP(), []int{9}
}

func (x *ManagerRenamed) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ManagerRenamed) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Event when a new conversation is created
type ConversationCreated struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ManagerId      string                 `protobuf:"bytes,3,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Context        map[string]string      `protobuf:"bytes,5,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationCreated) Reset() {
	*x = ConversationCreated{}
	mi := &file_managerspb_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationCreated) ProtoMessage() {}

func (x *ConversationCreated) ProtoReflect() protoreflect.Message {
	mi := &file_managerspb_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationCreated.ProtoReflect.Descriptor instead.
func (*ConversationCreated) Descriptor() ([]byte, []int) {
	return file_managerspb_events_proto_rawDescGZIP(), []int{10}
}

func (x *ConversationCreated) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationCreated) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConversationCreated) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *ConversationCreated) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ConversationCreated) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

// Event when a message is added to a conversation
type MessageAdded struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Message        *ConversationMessage   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ManagerId      string                 `protobuf:"bytes,3,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	Timestamp      string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageAdded) Reset() {
	*x = MessageAdded{}
	mi := &file_managerspb_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAdded) ProtoMessage() {}

func (x *MessageAdded) ProtoReflect() protoreflect.Message {
	mi := &file_managerspb_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAdded.ProtoReflect.Descriptor instead.
func (*MessageAdded) Descriptor() ([]byte, []int) {
	return file_managerspb_events_proto_rawDescGZIP(), []int{11}
}

func (x *MessageAdded) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageAdded) GetMessage() *ConversationMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MessageAdded) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *MessageAdded) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// Event when conversation context is updated
type ConversationContextUpdated struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ManagerId      string                 `protobuf:"bytes,2,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	Context        map[string]string      `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UpdatedAt      string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationContextUpdated) Reset() {
	*x = ConversationContextUpdated{}
	mi := &file_managerspb_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationContextUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationContextUpdated) ProtoMessage() {}

func (x *ConversationContextUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_managerspb_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationContextUpdated.ProtoReflect.Descriptor instead.
func (*ConversationContextUpdated) Descriptor() ([]byte, []int) {
	return file_managerspb_events_proto_rawDescGZIP(), []int{12}
}

func (x *ConversationContextUpdated) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationContextUpdated) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *ConversationContextUpdated) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ConversationContextUpdated) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Event when a conversation is archived
type ConversationArchived struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ManagerId      string                 `protobuf:"bytes,2,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	ArchivedAt     string                 `protobuf:"bytes,3,opt,name=archived_at,json=archivedAt,proto3" json:"archived_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationArchived) Reset() {
	*x = ConversationArchived{}
	mi := &file_managerspb_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationArchived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationArchived) ProtoMessage() {}

func (x *ConversationArchived) ProtoReflect() protoreflect.Message {
	mi := &file_managerspb_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationArchived.ProtoReflect.Descriptor instead.
func (*ConversationArchived) Descriptor() ([]byte, []int) {
	return file_managerspb_events_proto_rawDescGZIP(), []int{13}
}

func (x *ConversationArchived) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationArchived) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *ConversationArchived) GetArchivedAt() string {
	if x != nil {
		return x.ArchivedAt
	}
	return ""
}

var File_managerspb_events_proto protoreflect.FileDescriptor

const file_managerspb_events_proto_rawDesc = "" +
	"\n" +
	"\x17managerspb/events.proto\x12\n" +
	"managerspb\x1a\x1fmanagerspb/common_manager.proto\"#\n" +
	"\x11ManagerAuthorized\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc6\x02\n" +
	"\x0eManagerCreated\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12A\n" +
	"\fcapabilities\x18\x06 \x03(\x0e2\x1d.managerspb.ManagerCapabilityR\fcapabilities\x12 \n" +
	"\vtemperature\x18\a \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\b \x01(\x05R\tmaxTokens\x12#\n" +
	"\rsystem_prompt\x18\t \x01(\tR\fsystemPrompt\x12\x17\n" +
	"\auser_id\x18\n" +
	" \x01(\tR\x06userId\"@\n" +
	"\x10ManagerActivated\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\"B\n" +
	"\x12ManagerDeactivated\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\"\xb2\x01\n" +
	"\x1bManagerConfigurationUpdated\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vtemperature\x18\x02 \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\x05R\tmaxTokens\x12#\n" +
	"\rsystem_prompt\x18\x04 \x01(\tR\fsystemPrompt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"\x9a\x05\n" +
	"\x17ManagerRequestProcessed\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12J\n" +
	"\acontext\x18\x05 \x03(\v20.managerspb.ManagerRequestProcessed.ContextEntryR\acontext\x12!\n" +
	"\frequest_type\x18\x06 \x01(\tR\vrequestType\x12\x1f\n" +
	"\vresponse_id\x18\a \x01(\tR\n" +
	"responseId\x12)\n" +
	"\x10response_message\x18\b \x01(\tR\x0fresponseMessage\x12Z\n" +
	"\rresponse_data\x18\t \x03(\v25.managerspb.ManagerRequestProcessed.ResponseDataEntryR\fresponseData\x123\n" +
	"\aactions\x18\n" +
	" \x03(\v2\x19.managerspb.ManagerActionR\aactions\x12\x1c\n" +
	"\ttimestamp\x18\v \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"confidence\x18\r \x01(\x01R\n" +
	"confidence\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11ResponseDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"!\n" +
	"\x0fManagerLoggedIn\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\"\n" +
	"\x10ManagerLoggedOut\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"S\n" +
	"\x1bManagerParticipationToggled\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\rparticipating\x18\x02 \x01(\bR\rparticipating\"4\n" +
	"\x0eManagerRenamed\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x99\x02\n" +
	"\x13ConversationCreated\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x03 \x01(\tR\tmanagerId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12F\n" +
	"\acontext\x18\x05 \x03(\v2,.managerspb.ConversationCreated.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x01\n" +
	"\fMessageAdded\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x129\n" +
	"\amessage\x18\x02 \x01(\v2\x1f.managerspb.ConversationMessageR\amessage\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x03 \x01(\tR\tmanagerId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"\x8e\x02\n" +
	"\x1aConversationContextUpdated\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x02 \x01(\tR\tmanagerId\x12M\n" +
	"\acontext\x18\x03 \x03(\v23.managerspb.ConversationContextUpdated.ContextEntryR\acontext\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x7f\n" +
	"\x14ConversationArchived\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x02 \x01(\tR\tmanagerId\x12\x1f\n" +
	"\varchived_at\x18\x03 \x01(\tR\n" +
	"archivedAtB\x8f\x01\n" +
	"\x0ecom.managerspbB\vEventsProtoP\x01Z(middleman/managers/managerspb/managerspb\xa2\x02\x03MXX\xaa\x02\n" +
	"Managerspb\xca\x02\n" +
	"Managerspb\xe2\x02\x16Managerspb\\GPBMetadata\xea\x02\n" +
	"Managerspbb\x06proto3"

var (
	file_managerspb_events_proto_rawDescOnce sync.Once
	file_managerspb_events_proto_rawDescData []byte
)

func file_managerspb_events_proto_rawDescGZIP() []byte {
	file_managerspb_events_proto_rawDescOnce.Do(func() {
		file_managerspb_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_managerspb_events_proto_rawDesc), len(file_managerspb_events_proto_rawDesc)))
	})
	return file_managerspb_events_proto_rawDescData
}

var file_managerspb_events_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_managerspb_events_proto_goTypes = []any{
	(*ManagerAuthorized)(nil),           // 0: managerspb.ManagerAuthorized
	(*ManagerCreated)(nil),              // 1: managerspb.ManagerCreated
	(*ManagerActivated)(nil),            // 2: managerspb.ManagerActivated
	(*ManagerDeactivated)(nil),          // 3: managerspb.ManagerDeactivated
	(*ManagerConfigurationUpdated)(nil), // 4: managerspb.ManagerConfigurationUpdated
	(*ManagerRequestProcessed)(nil),     // 5: managerspb.ManagerRequestProcessed
	(*ManagerLoggedIn)(nil),             // 6: managerspb.ManagerLoggedIn
	(*ManagerLoggedOut)(nil),            // 7: managerspb.ManagerLoggedOut
	(*ManagerParticipationToggled)(nil), // 8: managerspb.ManagerParticipationToggled
	(*ManagerRenamed)(nil),              // 9: managerspb.ManagerRenamed
	(*ConversationCreated)(nil),         // 10: managerspb.ConversationCreated
	(*MessageAdded)(nil),                // 11: managerspb.MessageAdded
	(*ConversationContextUpdated)(nil),  // 12: managerspb.ConversationContextUpdated
	(*ConversationArchived)(nil),        // 13: managerspb.ConversationArchived
	nil,                                 // 14: managerspb.ManagerRequestProcessed.ContextEntry
	nil,                                 // 15: managerspb.ManagerRequestProcessed.ResponseDataEntry
	nil,                                 // 16: managerspb.ConversationCreated.ContextEntry
	nil,                                 // 17: managerspb.ConversationContextUpdated.ContextEntry
	(ManagerCapability)(0),              // 18: managerspb.ManagerCapability
	(*ManagerAction)(nil),               // 19: managerspb.ManagerAction
	(*ConversationMessage)(nil),         // 20: managerspb.ConversationMessage
}
var file_managerspb_events_proto_depIdxs = []int32{
	18, // 0: managerspb.ManagerCreated.capabilities:type_name -> managerspb.ManagerCapability
	14, // 1: managerspb.ManagerRequestProcessed.context:type_name -> managerspb.ManagerRequestProcessed.ContextEntry
	15, // 2: managerspb.ManagerRequestProcessed.response_data:type_name -> managerspb.ManagerRequestProcessed.ResponseDataEntry
	19, // 3: managerspb.ManagerRequestProcessed.actions:type_name -> managerspb.ManagerAction
	16, // 4: managerspb.ConversationCreated.context:type_name -> managerspb.ConversationCreated.ContextEntry
	20, // 5: managerspb.MessageAdded.message:type_name -> managerspb.ConversationMessage
	17, // 6: managerspb.ConversationContextUpdated.context:type_name -> managerspb.ConversationContextUpdated.ContextEntry
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_managerspb_events_proto_init() }
func file_managerspb_events_proto_init() {
	if File_managerspb_events_proto != nil {
		return
	}
	file_managerspb_common_manager_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_managerspb_events_proto_rawDesc), len(file_managerspb_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_managerspb_events_proto_goTypes,
		DependencyIndexes: file_managerspb_events_proto_depIdxs,
		MessageInfos:      file_managerspb_events_proto_msgTypes,
	}.Build()
	File_managerspb_events_proto = out.File
	file_managerspb_events_proto_goTypes = nil
	file_managerspb_events_proto_depIdxs = nil
}
