// Code generated by go-swagger; DO NOT EDIT.

package return_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"middleman/erp/erpclient/models"
)

// NewProcessReturnParams creates a new ProcessReturnParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewProcessReturnParams() *ProcessReturnParams {
	return &ProcessReturnParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewProcessReturnParamsWithTimeout creates a new ProcessReturnParams object
// with the ability to set a timeout on a request.
func NewProcessReturnParamsWithTimeout(timeout time.Duration) *ProcessReturnParams {
	return &ProcessReturnParams{
		timeout: timeout,
	}
}

// NewProcessReturnParamsWithContext creates a new ProcessReturnParams object
// with the ability to set a context for a request.
func NewProcessReturnParamsWithContext(ctx context.Context) *ProcessReturnParams {
	return &ProcessReturnParams{
		Context: ctx,
	}
}

// NewProcessReturnParamsWithHTTPClient creates a new ProcessReturnParams object
// with the ability to set a custom HTTPClient for a request.
func NewProcessReturnParamsWithHTTPClient(client *http.Client) *ProcessReturnParams {
	return &ProcessReturnParams{
		HTTPClient: client,
	}
}

/*
ProcessReturnParams contains all the parameters to send to the API endpoint

	for the process return operation.

	Typically these are written to a http.Request.
*/
type ProcessReturnParams struct {

	// Body.
	Body *models.ERPServiceProcessReturnBody

	// ConnectorID.
	ConnectorID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the process return params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProcessReturnParams) WithDefaults() *ProcessReturnParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the process return params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProcessReturnParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the process return params
func (o *ProcessReturnParams) WithTimeout(timeout time.Duration) *ProcessReturnParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the process return params
func (o *ProcessReturnParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the process return params
func (o *ProcessReturnParams) WithContext(ctx context.Context) *ProcessReturnParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the process return params
func (o *ProcessReturnParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the process return params
func (o *ProcessReturnParams) WithHTTPClient(client *http.Client) *ProcessReturnParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the process return params
func (o *ProcessReturnParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the process return params
func (o *ProcessReturnParams) WithBody(body *models.ERPServiceProcessReturnBody) *ProcessReturnParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the process return params
func (o *ProcessReturnParams) SetBody(body *models.ERPServiceProcessReturnBody) {
	o.Body = body
}

// WithConnectorID adds the connectorID to the process return params
func (o *ProcessReturnParams) WithConnectorID(connectorID string) *ProcessReturnParams {
	o.SetConnectorID(connectorID)
	return o
}

// SetConnectorID adds the connectorId to the process return params
func (o *ProcessReturnParams) SetConnectorID(connectorID string) {
	o.ConnectorID = connectorID
}

// WriteToRequest writes these params to a swagger request
func (o *ProcessReturnParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param connectorId
	if err := r.SetPathParam("connectorId", o.ConnectorID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
