// Code generated by go-swagger; DO NOT EDIT.

package shipping_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewShippingServiceGetShipmentHistoryParams creates a new ShippingServiceGetShipmentHistoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewShippingServiceGetShipmentHistoryParams() *ShippingServiceGetShipmentHistoryParams {
	return &ShippingServiceGetShipmentHistoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewShippingServiceGetShipmentHistoryParamsWithTimeout creates a new ShippingServiceGetShipmentHistoryParams object
// with the ability to set a timeout on a request.
func NewShippingServiceGetShipmentHistoryParamsWithTimeout(timeout time.Duration) *ShippingServiceGetShipmentHistoryParams {
	return &ShippingServiceGetShipmentHistoryParams{
		timeout: timeout,
	}
}

// NewShippingServiceGetShipmentHistoryParamsWithContext creates a new ShippingServiceGetShipmentHistoryParams object
// with the ability to set a context for a request.
func NewShippingServiceGetShipmentHistoryParamsWithContext(ctx context.Context) *ShippingServiceGetShipmentHistoryParams {
	return &ShippingServiceGetShipmentHistoryParams{
		Context: ctx,
	}
}

// NewShippingServiceGetShipmentHistoryParamsWithHTTPClient creates a new ShippingServiceGetShipmentHistoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewShippingServiceGetShipmentHistoryParamsWithHTTPClient(client *http.Client) *ShippingServiceGetShipmentHistoryParams {
	return &ShippingServiceGetShipmentHistoryParams{
		HTTPClient: client,
	}
}

/*
ShippingServiceGetShipmentHistoryParams contains all the parameters to send to the API endpoint

	for the shipping service get shipment history operation.

	Typically these are written to a http.Request.
*/
type ShippingServiceGetShipmentHistoryParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the shipping service get shipment history params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ShippingServiceGetShipmentHistoryParams) WithDefaults() *ShippingServiceGetShipmentHistoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the shipping service get shipment history params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ShippingServiceGetShipmentHistoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the shipping service get shipment history params
func (o *ShippingServiceGetShipmentHistoryParams) WithTimeout(timeout time.Duration) *ShippingServiceGetShipmentHistoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the shipping service get shipment history params
func (o *ShippingServiceGetShipmentHistoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the shipping service get shipment history params
func (o *ShippingServiceGetShipmentHistoryParams) WithContext(ctx context.Context) *ShippingServiceGetShipmentHistoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the shipping service get shipment history params
func (o *ShippingServiceGetShipmentHistoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the shipping service get shipment history params
func (o *ShippingServiceGetShipmentHistoryParams) WithHTTPClient(client *http.Client) *ShippingServiceGetShipmentHistoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the shipping service get shipment history params
func (o *ShippingServiceGetShipmentHistoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the shipping service get shipment history params
func (o *ShippingServiceGetShipmentHistoryParams) WithID(id string) *ShippingServiceGetShipmentHistoryParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the shipping service get shipment history params
func (o *ShippingServiceGetShipmentHistoryParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ShippingServiceGetShipmentHistoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
