// Code generated by go-swagger; DO NOT EDIT.

package shipping_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"middleman/shipping/shippingclient/models"
)

// ShippingServiceSchedulePickupReader is a Reader for the ShippingServiceSchedulePickup structure.
type ShippingServiceSchedulePickupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ShippingServiceSchedulePickupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewShippingServiceSchedulePickupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewShippingServiceSchedulePickupDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewShippingServiceSchedulePickupOK creates a ShippingServiceSchedulePickupOK with default headers values
func NewShippingServiceSchedulePickupOK() *ShippingServiceSchedulePickupOK {
	return &ShippingServiceSchedulePickupOK{}
}

/*
ShippingServiceSchedulePickupOK describes a response with status code 200, with default header values.

A successful response.
*/
type ShippingServiceSchedulePickupOK struct {
	Payload *models.ShippingpbSchedulePickupResponse
}

// IsSuccess returns true when this shipping service schedule pickup o k response has a 2xx status code
func (o *ShippingServiceSchedulePickupOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this shipping service schedule pickup o k response has a 3xx status code
func (o *ShippingServiceSchedulePickupOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this shipping service schedule pickup o k response has a 4xx status code
func (o *ShippingServiceSchedulePickupOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this shipping service schedule pickup o k response has a 5xx status code
func (o *ShippingServiceSchedulePickupOK) IsServerError() bool {
	return false
}

// IsCode returns true when this shipping service schedule pickup o k response a status code equal to that given
func (o *ShippingServiceSchedulePickupOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the shipping service schedule pickup o k response
func (o *ShippingServiceSchedulePickupOK) Code() int {
	return 200
}

func (o *ShippingServiceSchedulePickupOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/shipping/{id}/schedule-pickup][%d] shippingServiceSchedulePickupOK %s", 200, payload)
}

func (o *ShippingServiceSchedulePickupOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/shipping/{id}/schedule-pickup][%d] shippingServiceSchedulePickupOK %s", 200, payload)
}

func (o *ShippingServiceSchedulePickupOK) GetPayload() *models.ShippingpbSchedulePickupResponse {
	return o.Payload
}

func (o *ShippingServiceSchedulePickupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ShippingpbSchedulePickupResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewShippingServiceSchedulePickupDefault creates a ShippingServiceSchedulePickupDefault with default headers values
func NewShippingServiceSchedulePickupDefault(code int) *ShippingServiceSchedulePickupDefault {
	return &ShippingServiceSchedulePickupDefault{
		_statusCode: code,
	}
}

/*
ShippingServiceSchedulePickupDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ShippingServiceSchedulePickupDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this shipping service schedule pickup default response has a 2xx status code
func (o *ShippingServiceSchedulePickupDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this shipping service schedule pickup default response has a 3xx status code
func (o *ShippingServiceSchedulePickupDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this shipping service schedule pickup default response has a 4xx status code
func (o *ShippingServiceSchedulePickupDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this shipping service schedule pickup default response has a 5xx status code
func (o *ShippingServiceSchedulePickupDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this shipping service schedule pickup default response a status code equal to that given
func (o *ShippingServiceSchedulePickupDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the shipping service schedule pickup default response
func (o *ShippingServiceSchedulePickupDefault) Code() int {
	return o._statusCode
}

func (o *ShippingServiceSchedulePickupDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/shipping/{id}/schedule-pickup][%d] ShippingService_SchedulePickup default %s", o._statusCode, payload)
}

func (o *ShippingServiceSchedulePickupDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/shipping/{id}/schedule-pickup][%d] ShippingService_SchedulePickup default %s", o._statusCode, payload)
}

func (o *ShippingServiceSchedulePickupDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ShippingServiceSchedulePickupDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
