// Code generated by mockery v2.53.4. DO NOT EDIT.

package application

import (
	context "context"
	commands "middleman/offers/internal/application/commands"

	domain "middleman/offers/internal/domain"

	mock "github.com/stretchr/testify/mock"

	queries "middleman/offers/internal/application/queries"
)

// MockApp is an autogenerated mock type for the App type
type MockApp struct {
	mock.Mock
}

// AcceptBuyBackNegotiation provides a mock function with given fields: ctx, cmd
func (_m *MockApp) AcceptBuyBackNegotiation(ctx context.Context, cmd commands.AcceptBuyBackNegotiation) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AcceptBuyBackNegotiation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AcceptBuyBackNegotiation) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AcceptBuyNowNegotiation provides a mock function with given fields: ctx, cmd
func (_m *MockApp) AcceptBuyNowNegotiation(ctx context.Context, cmd commands.AcceptBuyNowNegotiation) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AcceptBuyNowNegotiation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AcceptBuyNowNegotiation) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AcceptLeaseNegotiation provides a mock function with given fields: ctx, cmd
func (_m *MockApp) AcceptLeaseNegotiation(ctx context.Context, cmd commands.AcceptLeaseNegotiation) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AcceptLeaseNegotiation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AcceptLeaseNegotiation) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AcceptOffer provides a mock function with given fields: ctx, cmd
func (_m *MockApp) AcceptOffer(ctx context.Context, cmd commands.AcceptOffer) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AcceptOffer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AcceptOffer) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AcceptReservationNegotiation provides a mock function with given fields: ctx, cmd
func (_m *MockApp) AcceptReservationNegotiation(ctx context.Context, cmd commands.AcceptReservationNegotiation) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AcceptReservationNegotiation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AcceptReservationNegotiation) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ActivateOffer provides a mock function with given fields: ctx, cmd
func (_m *MockApp) ActivateOffer(ctx context.Context, cmd commands.ActivateOffer) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for ActivateOffer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.ActivateOffer) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CancelBuyBack provides a mock function with given fields: ctx, cmd
func (_m *MockApp) CancelBuyBack(ctx context.Context, cmd commands.CancelBuyBack) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CancelBuyBack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CancelBuyBack) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CancelBuyNow provides a mock function with given fields: ctx, cmd
func (_m *MockApp) CancelBuyNow(ctx context.Context, cmd commands.CancelBuyNow) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CancelBuyNow")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CancelBuyNow) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CancelLease provides a mock function with given fields: ctx, cmd
func (_m *MockApp) CancelLease(ctx context.Context, cmd commands.CancelLease) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CancelLease")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CancelLease) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CancelReservation provides a mock function with given fields: ctx, cmd
func (_m *MockApp) CancelReservation(ctx context.Context, cmd commands.CancelReservation) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CancelReservation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CancelReservation) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CloseOffer provides a mock function with given fields: ctx, cmd
func (_m *MockApp) CloseOffer(ctx context.Context, cmd commands.CloseOffer) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CloseOffer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CloseOffer) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConfirmBuyNow provides a mock function with given fields: ctx, cmd
func (_m *MockApp) ConfirmBuyNow(ctx context.Context, cmd commands.ConfirmBuyNow) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmBuyNow")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.ConfirmBuyNow) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBuyBack provides a mock function with given fields: ctx, cmd
func (_m *MockApp) CreateBuyBack(ctx context.Context, cmd commands.CreateBuyBack) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CreateBuyBack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CreateBuyBack) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBuyNow provides a mock function with given fields: ctx, cmd
func (_m *MockApp) CreateBuyNow(ctx context.Context, cmd commands.CreateBuyNow) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CreateBuyNow")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CreateBuyNow) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateLease provides a mock function with given fields: ctx, cmd
func (_m *MockApp) CreateLease(ctx context.Context, cmd commands.CreateLease) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CreateLease")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CreateLease) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateOffer provides a mock function with given fields: ctx, cmd
func (_m *MockApp) CreateOffer(ctx context.Context, cmd commands.CreateOffer) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CreateOffer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CreateOffer) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateReservation provides a mock function with given fields: ctx, cmd
func (_m *MockApp) CreateReservation(ctx context.Context, cmd commands.CreateReservation) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CreateReservation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CreateReservation) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeclineBuyBackNegotiation provides a mock function with given fields: ctx, cmd
func (_m *MockApp) DeclineBuyBackNegotiation(ctx context.Context, cmd commands.DeclineBuyBackNegotiation) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for DeclineBuyBackNegotiation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.DeclineBuyBackNegotiation) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeclineBuyNowNegotiation provides a mock function with given fields: ctx, cmd
func (_m *MockApp) DeclineBuyNowNegotiation(ctx context.Context, cmd commands.DeclineBuyNowNegotiation) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for DeclineBuyNowNegotiation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.DeclineBuyNowNegotiation) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeclineLeaseNegotiation provides a mock function with given fields: ctx, cmd
func (_m *MockApp) DeclineLeaseNegotiation(ctx context.Context, cmd commands.DeclineLeaseNegotiation) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for DeclineLeaseNegotiation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.DeclineLeaseNegotiation) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeclineReservationNegotiation provides a mock function with given fields: ctx, cmd
func (_m *MockApp) DeclineReservationNegotiation(ctx context.Context, cmd commands.DeclineReservationNegotiation) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for DeclineReservationNegotiation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.DeclineReservationNegotiation) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DefaultLease provides a mock function with given fields: ctx, cmd
func (_m *MockApp) DefaultLease(ctx context.Context, cmd commands.DefaultLease) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for DefaultLease")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.DefaultLease) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EndLease provides a mock function with given fields: ctx, cmd
func (_m *MockApp) EndLease(ctx context.Context, cmd commands.EndLease) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for EndLease")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.EndLease) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExecuteLeaseBuyout provides a mock function with given fields: ctx, cmd
func (_m *MockApp) ExecuteLeaseBuyout(ctx context.Context, cmd commands.ExecuteLeaseBuyout) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteLeaseBuyout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.ExecuteLeaseBuyout) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExpireBuyBack provides a mock function with given fields: ctx, cmd
func (_m *MockApp) ExpireBuyBack(ctx context.Context, cmd commands.ExpireBuyBack) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for ExpireBuyBack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.ExpireBuyBack) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExpireReservation provides a mock function with given fields: ctx, cmd
func (_m *MockApp) ExpireReservation(ctx context.Context, cmd commands.ExpireReservation) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for ExpireReservation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.ExpireReservation) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOffer provides a mock function with given fields: ctx, query
func (_m *MockApp) GetOffer(ctx context.Context, query queries.GetOffer) (*domain.Offer, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetOffer")
	}

	var r0 *domain.Offer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetOffer) (*domain.Offer, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetOffer) *domain.Offer); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Offer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetOffer) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOffers provides a mock function with given fields: ctx, query
func (_m *MockApp) ListOffers(ctx context.Context, query queries.ListOffers) ([]*domain.Offer, int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for ListOffers")
	}

	var r0 []*domain.Offer
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.ListOffers) ([]*domain.Offer, int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.ListOffers) []*domain.Offer); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Offer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.ListOffers) int64); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, queries.ListOffers) error); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MakeLeasePayment provides a mock function with given fields: ctx, cmd
func (_m *MockApp) MakeLeasePayment(ctx context.Context, cmd commands.MakeLeasePayment) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for MakeLeasePayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.MakeLeasePayment) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RedeemBuyBack provides a mock function with given fields: ctx, cmd
func (_m *MockApp) RedeemBuyBack(ctx context.Context, cmd commands.RedeemBuyBack) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for RedeemBuyBack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.RedeemBuyBack) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RedeemReservation provides a mock function with given fields: ctx, cmd
func (_m *MockApp) RedeemReservation(ctx context.Context, cmd commands.RedeemReservation) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for RedeemReservation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.RedeemReservation) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RequestBuyBackNegotiation provides a mock function with given fields: ctx, cmd
func (_m *MockApp) RequestBuyBackNegotiation(ctx context.Context, cmd commands.RequestBuyBackNegotiation) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for RequestBuyBackNegotiation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.RequestBuyBackNegotiation) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RequestBuyNowNegotiation provides a mock function with given fields: ctx, cmd
func (_m *MockApp) RequestBuyNowNegotiation(ctx context.Context, cmd commands.RequestBuyNowNegotiation) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for RequestBuyNowNegotiation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.RequestBuyNowNegotiation) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RequestLeaseNegotiation provides a mock function with given fields: ctx, cmd
func (_m *MockApp) RequestLeaseNegotiation(ctx context.Context, cmd commands.RequestLeaseNegotiation) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for RequestLeaseNegotiation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.RequestLeaseNegotiation) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RequestReservationNegotiation provides a mock function with given fields: ctx, cmd
func (_m *MockApp) RequestReservationNegotiation(ctx context.Context, cmd commands.RequestReservationNegotiation) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for RequestReservationNegotiation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.RequestReservationNegotiation) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StartLease provides a mock function with given fields: ctx, cmd
func (_m *MockApp) StartLease(ctx context.Context, cmd commands.StartLease) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for StartLease")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.StartLease) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockApp creates a new instance of MockApp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApp(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApp {
	mock := &MockApp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
