// Code generated by go-swagger; DO NOT EDIT.

package lease

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new lease API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new lease API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new lease API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for lease API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CreateLease(params *CreateLeaseParams, opts ...ClientOption) (*CreateLeaseOK, error)

	DefaultLease(params *DefaultLeaseParams, opts ...ClientOption) (*DefaultLeaseOK, error)

	EndLease(params *EndLeaseParams, opts ...ClientOption) (*EndLeaseOK, error)

	ExecuteLeaseBuyout(params *ExecuteLeaseBuyoutParams, opts ...ClientOption) (*ExecuteLeaseBuyoutOK, error)

	MakeLeasePayment(params *MakeLeasePaymentParams, opts ...ClientOption) (*MakeLeasePaymentOK, error)

	StartLease(params *StartLeaseParams, opts ...ClientOption) (*StartLeaseOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
CreateLease creates a lease aggregator for a chosen offer
*/
func (a *Client) CreateLease(params *CreateLeaseParams, opts ...ClientOption) (*CreateLeaseOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateLeaseParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "createLease",
		Method:             "POST",
		PathPattern:        "/api/offers/lease",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateLeaseReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateLeaseOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*CreateLeaseDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
DefaultLease defaults a lease for non payment
*/
func (a *Client) DefaultLease(params *DefaultLeaseParams, opts ...ClientOption) (*DefaultLeaseOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDefaultLeaseParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "defaultLease",
		Method:             "POST",
		PathPattern:        "/api/offers/lease/{leaseId}/default",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DefaultLeaseReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DefaultLeaseOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*DefaultLeaseDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
EndLease ends a lease normally e g completed
*/
func (a *Client) EndLease(params *EndLeaseParams, opts ...ClientOption) (*EndLeaseOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewEndLeaseParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "endLease",
		Method:             "POST",
		PathPattern:        "/api/offers/lease/{leaseId}/end",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &EndLeaseReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*EndLeaseOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*EndLeaseDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ExecuteLeaseBuyout executes a lease buyout if allowed
*/
func (a *Client) ExecuteLeaseBuyout(params *ExecuteLeaseBuyoutParams, opts ...ClientOption) (*ExecuteLeaseBuyoutOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewExecuteLeaseBuyoutParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "executeLeaseBuyout",
		Method:             "POST",
		PathPattern:        "/api/offers/lease/{leaseId}/buyout",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ExecuteLeaseBuyoutReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ExecuteLeaseBuyoutOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ExecuteLeaseBuyoutDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
MakeLeasePayment makes a monthly payment for an active lease
*/
func (a *Client) MakeLeasePayment(params *MakeLeasePaymentParams, opts ...ClientOption) (*MakeLeasePaymentOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewMakeLeasePaymentParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "makeLeasePayment",
		Method:             "POST",
		PathPattern:        "/api/offers/lease/{leaseId}/payment",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &MakeLeasePaymentReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*MakeLeasePaymentOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*MakeLeasePaymentDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
StartLease starts a lease transition from pending to active
*/
func (a *Client) StartLease(params *StartLeaseParams, opts ...ClientOption) (*StartLeaseOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStartLeaseParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "startLease",
		Method:             "POST",
		PathPattern:        "/api/offers/lease/{leaseId}/start",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &StartLeaseReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*StartLeaseOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*StartLeaseDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
