// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCategoriesParams creates a new GetCategoriesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCategoriesParams() *GetCategoriesParams {
	return &GetCategoriesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCategoriesParamsWithTimeout creates a new GetCategoriesParams object
// with the ability to set a timeout on a request.
func NewGetCategoriesParamsWithTimeout(timeout time.Duration) *GetCategoriesParams {
	return &GetCategoriesParams{
		timeout: timeout,
	}
}

// NewGetCategoriesParamsWithContext creates a new GetCategoriesParams object
// with the ability to set a context for a request.
func NewGetCategoriesParamsWithContext(ctx context.Context) *GetCategoriesParams {
	return &GetCategoriesParams{
		Context: ctx,
	}
}

// NewGetCategoriesParamsWithHTTPClient creates a new GetCategoriesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCategoriesParamsWithHTTPClient(client *http.Client) *GetCategoriesParams {
	return &GetCategoriesParams{
		HTTPClient: client,
	}
}

/*
GetCategoriesParams contains all the parameters to send to the API endpoint

	for the get categories operation.

	Typically these are written to a http.Request.
*/
type GetCategoriesParams struct {

	// CategoryType.
	CategoryType *string

	// Lang.
	Lang *string

	// Page.
	//
	// Format: int64
	Page *string

	// PageSize.
	//
	// Format: int64
	PageSize *string

	// SortBy.
	SortBy *string

	// SortOrder.
	SortOrder *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get categories params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCategoriesParams) WithDefaults() *GetCategoriesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get categories params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCategoriesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get categories params
func (o *GetCategoriesParams) WithTimeout(timeout time.Duration) *GetCategoriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get categories params
func (o *GetCategoriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get categories params
func (o *GetCategoriesParams) WithContext(ctx context.Context) *GetCategoriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get categories params
func (o *GetCategoriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get categories params
func (o *GetCategoriesParams) WithHTTPClient(client *http.Client) *GetCategoriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get categories params
func (o *GetCategoriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCategoryType adds the categoryType to the get categories params
func (o *GetCategoriesParams) WithCategoryType(categoryType *string) *GetCategoriesParams {
	o.SetCategoryType(categoryType)
	return o
}

// SetCategoryType adds the categoryType to the get categories params
func (o *GetCategoriesParams) SetCategoryType(categoryType *string) {
	o.CategoryType = categoryType
}

// WithLang adds the lang to the get categories params
func (o *GetCategoriesParams) WithLang(lang *string) *GetCategoriesParams {
	o.SetLang(lang)
	return o
}

// SetLang adds the lang to the get categories params
func (o *GetCategoriesParams) SetLang(lang *string) {
	o.Lang = lang
}

// WithPage adds the page to the get categories params
func (o *GetCategoriesParams) WithPage(page *string) *GetCategoriesParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get categories params
func (o *GetCategoriesParams) SetPage(page *string) {
	o.Page = page
}

// WithPageSize adds the pageSize to the get categories params
func (o *GetCategoriesParams) WithPageSize(pageSize *string) *GetCategoriesParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the get categories params
func (o *GetCategoriesParams) SetPageSize(pageSize *string) {
	o.PageSize = pageSize
}

// WithSortBy adds the sortBy to the get categories params
func (o *GetCategoriesParams) WithSortBy(sortBy *string) *GetCategoriesParams {
	o.SetSortBy(sortBy)
	return o
}

// SetSortBy adds the sortBy to the get categories params
func (o *GetCategoriesParams) SetSortBy(sortBy *string) {
	o.SortBy = sortBy
}

// WithSortOrder adds the sortOrder to the get categories params
func (o *GetCategoriesParams) WithSortOrder(sortOrder *string) *GetCategoriesParams {
	o.SetSortOrder(sortOrder)
	return o
}

// SetSortOrder adds the sortOrder to the get categories params
func (o *GetCategoriesParams) SetSortOrder(sortOrder *string) {
	o.SortOrder = sortOrder
}

// WriteToRequest writes these params to a swagger request
func (o *GetCategoriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CategoryType != nil {

		// query param categoryType
		var qrCategoryType string

		if o.CategoryType != nil {
			qrCategoryType = *o.CategoryType
		}
		qCategoryType := qrCategoryType
		if qCategoryType != "" {

			if err := r.SetQueryParam("categoryType", qCategoryType); err != nil {
				return err
			}
		}
	}

	if o.Lang != nil {

		// query param lang
		var qrLang string

		if o.Lang != nil {
			qrLang = *o.Lang
		}
		qLang := qrLang
		if qLang != "" {

			if err := r.SetQueryParam("lang", qLang); err != nil {
				return err
			}
		}
	}

	if o.Page != nil {

		// query param page
		var qrPage string

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := qrPage
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.PageSize != nil {

		// query param pageSize
		var qrPageSize string

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := qrPageSize
		if qPageSize != "" {

			if err := r.SetQueryParam("pageSize", qPageSize); err != nil {
				return err
			}
		}
	}

	if o.SortBy != nil {

		// query param sortBy
		var qrSortBy string

		if o.SortBy != nil {
			qrSortBy = *o.SortBy
		}
		qSortBy := qrSortBy
		if qSortBy != "" {

			if err := r.SetQueryParam("sortBy", qSortBy); err != nil {
				return err
			}
		}
	}

	if o.SortOrder != nil {

		// query param sortOrder
		var qrSortOrder string

		if o.SortOrder != nil {
			qrSortOrder = *o.SortOrder
		}
		qSortOrder := qrSortOrder
		if qSortOrder != "" {

			if err := r.SetQueryParam("sortOrder", qSortOrder); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
