apiVersion: v1
kind: Secret
metadata:
  # Name referenced by the Jenkins Deployment's environment variables
  name: jenkins-registry-creds
  # Must be in the same namespace as the Jenkins Deployment
  namespace: jenkins
type: Opaque # Standard type for key-value secrets
data:
  username: c2ltb25nb2xhZG1pbg== # Example: dXNlcm5hbWU=
  password: a2xqc2FkODlha25zbWRmbGE2OWFuMzg5NmFsYWtoZGZh # Example: cGFzc3dvcmQ=

