// Code generated by mockery v2.53.0. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCatalogRepository is an autogenerated mock type for the CatalogRepository type
type MockCatalogRepository struct {
	mock.Mock
}

// AddStream provides a mock function with given fields: ctx, id, name, description, basePrice, userSellerID, categoryID, categorySlug, brand, condition, model, tags, manageStock, stock, sku, attributes, weight, height, width, depth, status, negotiable, userType, middlemanService, shippingCost, hasVariants, options, thumbnail, lat, long
func (_m *MockCatalogRepository) AddStream(ctx context.Context, id string, name string, description string, basePrice int64, userSellerID string, categoryID string, categorySlug string, brand string, condition StreamCondition, model string, tags []string, manageStock bool, stock int64, sku string, attributes []Attribute, weight int64, height int64, width int64, depth int64, status StreamStatus, negotiable bool, userType UserType, middlemanService bool, shippingCost int64, hasVariants bool, options []Option, thumbnail string, lat float64, long float64) error {
	ret := _m.Called(ctx, id, name, description, basePrice, userSellerID, categoryID, categorySlug, brand, condition, model, tags, manageStock, stock, sku, attributes, weight, height, width, depth, status, negotiable, userType, middlemanService, shippingCost, hasVariants, options, thumbnail, lat, long)

	if len(ret) == 0 {
		panic("no return value specified for AddStream")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64, string, string, string, string, StreamCondition, string, []string, bool, int64, string, []Attribute, int64, int64, int64, int64, StreamStatus, bool, UserType, bool, int64, bool, []Option, string, float64, float64) error); ok {
		r0 = rf(ctx, id, name, description, basePrice, userSellerID, categoryID, categorySlug, brand, condition, model, tags, manageStock, stock, sku, attributes, weight, height, width, depth, status, negotiable, userType, middlemanService, shippingCost, hasVariants, options, thumbnail, lat, long)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AdjustStock provides a mock function with given fields: ctx, productID, userSellerID, oldStock, newStock
func (_m *MockCatalogRepository) AdjustStock(ctx context.Context, productID string, userSellerID string, oldStock int64, newStock int64) error {
	ret := _m.Called(ctx, productID, userSellerID, oldStock, newStock)

	if len(ret) == 0 {
		panic("no return value specified for AdjustStock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, int64) error); ok {
		r0 = rf(ctx, productID, userSellerID, oldStock, newStock)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ArchiveStream provides a mock function with given fields: ctx, productID, userSellerID
func (_m *MockCatalogRepository) ArchiveStream(ctx context.Context, productID string, userSellerID string) error {
	ret := _m.Called(ctx, productID, userSellerID)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveStream")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, productID, userSellerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: ctx, productID
func (_m *MockCatalogRepository) Find(ctx context.Context, productID string) (*CatalogStream, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *CatalogStream
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*CatalogStream, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *CatalogStream); ok {
		r0 = rf(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CatalogStream)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCatalog provides a mock function with given fields: ctx, userSellerID, page, pageSize, sortBy, sortOrder
func (_m *MockCatalogRepository) GetCatalog(ctx context.Context, userSellerID string, page int64, pageSize int64, sortBy string, sortOrder string) ([]*CatalogStream, int64, error) {
	ret := _m.Called(ctx, userSellerID, page, pageSize, sortBy, sortOrder)

	if len(ret) == 0 {
		panic("no return value specified for GetCatalog")
	}

	var r0 []*CatalogStream
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string, string) ([]*CatalogStream, int64, error)); ok {
		return rf(ctx, userSellerID, page, pageSize, sortBy, sortOrder)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string, string) []*CatalogStream); ok {
		r0 = rf(ctx, userSellerID, page, pageSize, sortBy, sortOrder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*CatalogStream)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64, string, string) int64); ok {
		r1 = rf(ctx, userSellerID, page, pageSize, sortBy, sortOrder)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int64, int64, string, string) error); ok {
		r2 = rf(ctx, userSellerID, page, pageSize, sortBy, sortOrder)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetStreamBySKU provides a mock function with given fields: ctx, sku
func (_m *MockCatalogRepository) GetStreamBySKU(ctx context.Context, sku string) (*CatalogStream, error) {
	ret := _m.Called(ctx, sku)

	if len(ret) == 0 {
		panic("no return value specified for GetStreamBySKU")
	}

	var r0 *CatalogStream
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*CatalogStream, error)); ok {
		return rf(ctx, sku)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *CatalogStream); ok {
		r0 = rf(ctx, sku)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CatalogStream)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sku)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStreams provides a mock function with given fields: ctx, page, pageSize, sortBy, sortOrder
func (_m *MockCatalogRepository) GetStreams(ctx context.Context, page int64, pageSize int64, sortBy string, sortOrder string) ([]*CatalogStream, int64, error) {
	ret := _m.Called(ctx, page, pageSize, sortBy, sortOrder)

	if len(ret) == 0 {
		panic("no return value specified for GetStreams")
	}

	var r0 []*CatalogStream
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string, string) ([]*CatalogStream, int64, error)); ok {
		return rf(ctx, page, pageSize, sortBy, sortOrder)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string, string) []*CatalogStream); ok {
		r0 = rf(ctx, page, pageSize, sortBy, sortOrder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*CatalogStream)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, string, string) int64); ok {
		r1 = rf(ctx, page, pageSize, sortBy, sortOrder)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, int64, string, string) error); ok {
		r2 = rf(ctx, page, pageSize, sortBy, sortOrder)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetStreamsByCategory provides a mock function with given fields: ctx, categoryID, page, pageSize, sortBy, sortOrder
func (_m *MockCatalogRepository) GetStreamsByCategory(ctx context.Context, categoryID string, page int64, pageSize int64, sortBy string, sortOrder string) ([]*CatalogStream, int64, error) {
	ret := _m.Called(ctx, categoryID, page, pageSize, sortBy, sortOrder)

	if len(ret) == 0 {
		panic("no return value specified for GetStreamsByCategory")
	}

	var r0 []*CatalogStream
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string, string) ([]*CatalogStream, int64, error)); ok {
		return rf(ctx, categoryID, page, pageSize, sortBy, sortOrder)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string, string) []*CatalogStream); ok {
		r0 = rf(ctx, categoryID, page, pageSize, sortBy, sortOrder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*CatalogStream)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64, string, string) int64); ok {
		r1 = rf(ctx, categoryID, page, pageSize, sortBy, sortOrder)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int64, int64, string, string) error); ok {
		r2 = rf(ctx, categoryID, page, pageSize, sortBy, sortOrder)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetStreamsByCategorySlug provides a mock function with given fields: ctx, categorySlug, page, pageSize, sortBy, sortOrder
func (_m *MockCatalogRepository) GetStreamsByCategorySlug(ctx context.Context, categorySlug string, page int64, pageSize int64, sortBy string, sortOrder string) ([]*CatalogStream, int64, error) {
	ret := _m.Called(ctx, categorySlug, page, pageSize, sortBy, sortOrder)

	if len(ret) == 0 {
		panic("no return value specified for GetStreamsByCategorySlug")
	}

	var r0 []*CatalogStream
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string, string) ([]*CatalogStream, int64, error)); ok {
		return rf(ctx, categorySlug, page, pageSize, sortBy, sortOrder)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string, string) []*CatalogStream); ok {
		r0 = rf(ctx, categorySlug, page, pageSize, sortBy, sortOrder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*CatalogStream)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64, string, string) int64); ok {
		r1 = rf(ctx, categorySlug, page, pageSize, sortBy, sortOrder)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int64, int64, string, string) error); ok {
		r2 = rf(ctx, categorySlug, page, pageSize, sortBy, sortOrder)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetStreamsBySKUs provides a mock function with given fields: ctx, skus
func (_m *MockCatalogRepository) GetStreamsBySKUs(ctx context.Context, skus []string) ([]*CatalogStream, error) {
	ret := _m.Called(ctx, skus)

	if len(ret) == 0 {
		panic("no return value specified for GetStreamsBySKUs")
	}

	var r0 []*CatalogStream
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*CatalogStream, error)); ok {
		return rf(ctx, skus)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*CatalogStream); ok {
		r0 = rf(ctx, skus)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*CatalogStream)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, skus)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStreamsWithFilters provides a mock function with given fields: ctx, name, categoryId, categorySlug, minPrice, maxPrice, brand, condition, model, tags, manageStock, minStock, maxStock, sku, status, negotiable, userType, middlemanService, hasVariants, shippingCost, minWeight, maxWeight, minHeight, maxHeight, minWidth, maxWidth, minDepth, maxDepth, offset, limit, lat, lng, radius, page, pageSize, sortBy, sortOrder
func (_m *MockCatalogRepository) GetStreamsWithFilters(ctx context.Context, name string, categoryId string, categorySlug string, minPrice int64, maxPrice int64, brand string, condition string, model string, tags []string, manageStock bool, minStock int64, maxStock int64, sku string, status string, negotiable bool, userType string, middlemanService bool, hasVariants bool, shippingCost int64, minWeight int64, maxWeight int64, minHeight int64, maxHeight int64, minWidth int64, maxWidth int64, minDepth int64, maxDepth int64, offset int64, limit int64, lat float64, lng float64, radius int64, page int64, pageSize int64, sortBy string, sortOrder string) ([]*CatalogStream, int64, error) {
	ret := _m.Called(ctx, name, categoryId, categorySlug, minPrice, maxPrice, brand, condition, model, tags, manageStock, minStock, maxStock, sku, status, negotiable, userType, middlemanService, hasVariants, shippingCost, minWeight, maxWeight, minHeight, maxHeight, minWidth, maxWidth, minDepth, maxDepth, offset, limit, lat, lng, radius, page, pageSize, sortBy, sortOrder)

	if len(ret) == 0 {
		panic("no return value specified for GetStreamsWithFilters")
	}

	var r0 []*CatalogStream
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64, int64, string, string, string, []string, bool, int64, int64, string, string, bool, string, bool, bool, int64, int64, int64, int64, int64, int64, int64, int64, int64, int64, int64, float64, float64, int64, int64, int64, string, string) ([]*CatalogStream, int64, error)); ok {
		return rf(ctx, name, categoryId, categorySlug, minPrice, maxPrice, brand, condition, model, tags, manageStock, minStock, maxStock, sku, status, negotiable, userType, middlemanService, hasVariants, shippingCost, minWeight, maxWeight, minHeight, maxHeight, minWidth, maxWidth, minDepth, maxDepth, offset, limit, lat, lng, radius, page, pageSize, sortBy, sortOrder)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64, int64, string, string, string, []string, bool, int64, int64, string, string, bool, string, bool, bool, int64, int64, int64, int64, int64, int64, int64, int64, int64, int64, int64, float64, float64, int64, int64, int64, string, string) []*CatalogStream); ok {
		r0 = rf(ctx, name, categoryId, categorySlug, minPrice, maxPrice, brand, condition, model, tags, manageStock, minStock, maxStock, sku, status, negotiable, userType, middlemanService, hasVariants, shippingCost, minWeight, maxWeight, minHeight, maxHeight, minWidth, maxWidth, minDepth, maxDepth, offset, limit, lat, lng, radius, page, pageSize, sortBy, sortOrder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*CatalogStream)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int64, int64, string, string, string, []string, bool, int64, int64, string, string, bool, string, bool, bool, int64, int64, int64, int64, int64, int64, int64, int64, int64, int64, int64, float64, float64, int64, int64, int64, string, string) int64); ok {
		r1 = rf(ctx, name, categoryId, categorySlug, minPrice, maxPrice, brand, condition, model, tags, manageStock, minStock, maxStock, sku, status, negotiable, userType, middlemanService, hasVariants, shippingCost, minWeight, maxWeight, minHeight, maxHeight, minWidth, maxWidth, minDepth, maxDepth, offset, limit, lat, lng, radius, page, pageSize, sortBy, sortOrder)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, int64, int64, string, string, string, []string, bool, int64, int64, string, string, bool, string, bool, bool, int64, int64, int64, int64, int64, int64, int64, int64, int64, int64, int64, float64, float64, int64, int64, int64, string, string) error); ok {
		r2 = rf(ctx, name, categoryId, categorySlug, minPrice, maxPrice, brand, condition, model, tags, manageStock, minStock, maxStock, sku, status, negotiable, userType, middlemanService, hasVariants, shippingCost, minWeight, maxWeight, minHeight, maxHeight, minWidth, maxWidth, minDepth, maxDepth, offset, limit, lat, lng, radius, page, pageSize, sortBy, sortOrder)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetPublicCatalog provides a mock function with given fields: ctx, userSellerID, page, pageSize, sortBy, sortOrder
func (_m *MockCatalogRepository) GetPublicCatalog(ctx context.Context, userSellerID string, page int64, pageSize int64, sortBy string, sortOrder string) ([]*CatalogStream, int64, error) {
	ret := _m.Called(ctx, userSellerID, page, pageSize, sortBy, sortOrder)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicCatalog")
	}

	var r0 []*CatalogStream
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string, string) ([]*CatalogStream, int64, error)); ok {
		return rf(ctx, userSellerID, page, pageSize, sortBy, sortOrder)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string, string) []*CatalogStream); ok {
		r0 = rf(ctx, userSellerID, page, pageSize, sortBy, sortOrder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*CatalogStream)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64, string, string) int64); ok {
		r1 = rf(ctx, userSellerID, page, pageSize, sortBy, sortOrder)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int64, int64, string, string) error); ok {
		r2 = rf(ctx, userSellerID, page, pageSize, sortBy, sortOrder)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MarkStreamLeased provides a mock function with given fields: ctx, productID, userSellerID
func (_m *MockCatalogRepository) MarkStreamLeased(ctx context.Context, productID string, userSellerID string) error {
	ret := _m.Called(ctx, productID, userSellerID)

	if len(ret) == 0 {
		panic("no return value specified for MarkStreamLeased")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, productID, userSellerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarkStreamPawned provides a mock function with given fields: ctx, productID, userSellerID
func (_m *MockCatalogRepository) MarkStreamPawned(ctx context.Context, productID string, userSellerID string) error {
	ret := _m.Called(ctx, productID, userSellerID)

	if len(ret) == 0 {
		panic("no return value specified for MarkStreamPawned")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, productID, userSellerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarkStreamSold provides a mock function with given fields: ctx, productID, userSellerID, finalPrice
func (_m *MockCatalogRepository) MarkStreamSold(ctx context.Context, productID string, userSellerID string, finalPrice int64) error {
	ret := _m.Called(ctx, productID, userSellerID, finalPrice)

	if len(ret) == 0 {
		panic("no return value specified for MarkStreamSold")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) error); ok {
		r0 = rf(ctx, productID, userSellerID, finalPrice)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RebrandStream provides a mock function with given fields: ctx, productID, newName, newDescription, newCategoryID, newCategorySlug, newBrand, newModel, newCondition, newTags
func (_m *MockCatalogRepository) RebrandStream(ctx context.Context, productID string, newName string, newDescription string, newCategoryID string, newCategorySlug string, newBrand string, newModel string, newCondition string, newTags []string) error {
	ret := _m.Called(ctx, productID, newName, newDescription, newCategoryID, newCategorySlug, newBrand, newModel, newCondition, newTags)

	if len(ret) == 0 {
		panic("no return value specified for RebrandStream")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string, string, string, []string) error); ok {
		r0 = rf(ctx, productID, newName, newDescription, newCategoryID, newCategorySlug, newBrand, newModel, newCondition, newTags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveStream provides a mock function with given fields: ctx, productID, userSellerID
func (_m *MockCatalogRepository) RemoveStream(ctx context.Context, productID string, userSellerID string) error {
	ret := _m.Called(ctx, productID, userSellerID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveStream")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, productID, userSellerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ToggleNegotiable provides a mock function with given fields: ctx, productID, userSellerID, currentValue
func (_m *MockCatalogRepository) ToggleNegotiable(ctx context.Context, productID string, userSellerID string, currentValue bool) error {
	ret := _m.Called(ctx, productID, userSellerID, currentValue)

	if len(ret) == 0 {
		panic("no return value specified for ToggleNegotiable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) error); ok {
		r0 = rf(ctx, productID, userSellerID, currentValue)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePrice provides a mock function with given fields: ctx, productID, oldPrice, newPrice
func (_m *MockCatalogRepository) UpdatePrice(ctx context.Context, productID string, oldPrice int64, newPrice int64) error {
	ret := _m.Called(ctx, productID, oldPrice, newPrice)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePrice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) error); ok {
		r0 = rf(ctx, productID, oldPrice, newPrice)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStream provides a mock function with given fields: ctx, productID, name, description, basePrice, categoryID, categorySlug, brand, condition, model, tags, manageStock, stock, sku, attributes, weight, height, width, depth, status, negotiable, userType, middlemanService, shippingCost, hasVariants, options, thumbnail, lat, lng
func (_m *MockCatalogRepository) UpdateStream(ctx context.Context, productID string, name string, description string, basePrice int64, categoryID string, categorySlug string, brand string, condition StreamCondition, model string, tags []string, manageStock bool, stock int64, sku string, attributes []Attribute, weight int64, height int64, width int64, depth int64, status StreamStatus, negotiable bool, userType UserType, middlemanService bool, shippingCost int64, hasVariants bool, options []Option, thumbnail string, lat float64, lng float64) error {
	ret := _m.Called(ctx, productID, name, description, basePrice, categoryID, categorySlug, brand, condition, model, tags, manageStock, stock, sku, attributes, weight, height, width, depth, status, negotiable, userType, middlemanService, shippingCost, hasVariants, options, thumbnail, lat, lng)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStream")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64, string, string, string, StreamCondition, string, []string, bool, int64, string, []Attribute, int64, int64, int64, int64, StreamStatus, bool, UserType, bool, int64, bool, []Option, string, float64, float64) error); ok {
		r0 = rf(ctx, productID, name, description, basePrice, categoryID, categorySlug, brand, condition, model, tags, manageStock, stock, sku, attributes, weight, height, width, depth, status, negotiable, userType, middlemanService, shippingCost, hasVariants, options, thumbnail, lat, lng)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateThumbnail provides a mock function with given fields: ctx, productID, thumbnail
func (_m *MockCatalogRepository) UpdateThumbnail(ctx context.Context, productID string, thumbnail string) error {
	ret := _m.Called(ctx, productID, thumbnail)

	if len(ret) == 0 {
		panic("no return value specified for UpdateThumbnail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, productID, thumbnail)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockCatalogRepository creates a new instance of MockCatalogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCatalogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCatalogRepository {
	mock := &MockCatalogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
