// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrderingpbOrderingServiceApproveOrderBody orderingpb ordering service approve order body
//
// swagger:model orderingpbOrderingServiceApproveOrderBody
type OrderingpbOrderingServiceApproveOrderBody struct {

	// shopping Id
	ShoppingID string `json:"shoppingId,omitempty"`
}

// Validate validates this orderingpb ordering service approve order body
func (m *OrderingpbOrderingServiceApproveOrderBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this orderingpb ordering service approve order body based on context it is used
func (m *OrderingpbOrderingServiceApproveOrderBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrderingpbOrderingServiceApproveOrderBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderingpbOrderingServiceApproveOrderBody) UnmarshalBinary(b []byte) error {
	var res OrderingpbOrderingServiceApproveOrderBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
