// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CategoriespbRemoveFilterResponse categoriespb remove filter response
//
// swagger:model categoriespbRemoveFilterResponse
type CategoriespbRemoveFilterResponse struct {

	// filter Id
	FilterID string `json:"filterId,omitempty"`
}

// Validate validates this categoriespb remove filter response
func (m *CategoriespbRemoveFilterResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this categoriespb remove filter response based on context it is used
func (m *CategoriespbRemoveFilterResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CategoriespbRemoveFilterResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CategoriespbRemoveFilterResponse) UnmarshalBinary(b []byte) error {
	var res CategoriespbRemoveFilterResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
