// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// SupportpbTicketCategory supportpb ticket category
//
// swagger:model supportpbTicketCategory
type SupportpbTicketCategory string

func NewSupportpbTicketCategory(value SupportpbTicketCategory) *SupportpbTicketCategory {
	return &value
}

// Pointer returns a pointer to a freshly-allocated SupportpbTicketCategory.
func (m SupportpbTicketCategory) Pointer() *SupportpbTicketCategory {
	return &m
}

const (

	// SupportpbTicketCategoryGENERALINQUIRY captures enum value "GENERAL_INQUIRY"
	SupportpbTicketCategoryGENERALINQUIRY SupportpbTicketCategory = "GENERAL_INQUIRY"

	// SupportpbTicketCategoryTECHNICALISSUE captures enum value "TECHNICAL_ISSUE"
	SupportpbTicketCategoryTECHNICALISSUE SupportpbTicketCategory = "TECHNICAL_ISSUE"

	// SupportpbTicketCategoryBILLINGISSUE captures enum value "BILLING_ISSUE"
	SupportpbTicketCategoryBILLINGISSUE SupportpbTicketCategory = "BILLING_ISSUE"

	// SupportpbTicketCategoryACCOUNTISSUE captures enum value "ACCOUNT_ISSUE"
	SupportpbTicketCategoryACCOUNTISSUE SupportpbTicketCategory = "ACCOUNT_ISSUE"

	// SupportpbTicketCategoryPRODUCTQUESTION captures enum value "PRODUCT_QUESTION"
	SupportpbTicketCategoryPRODUCTQUESTION SupportpbTicketCategory = "PRODUCT_QUESTION"

	// SupportpbTicketCategoryFEATUREREQUEST captures enum value "FEATURE_REQUEST"
	SupportpbTicketCategoryFEATUREREQUEST SupportpbTicketCategory = "FEATURE_REQUEST"

	// SupportpbTicketCategoryCOMPLAINT captures enum value "COMPLAINT"
	SupportpbTicketCategoryCOMPLAINT SupportpbTicketCategory = "COMPLAINT"

	// SupportpbTicketCategoryREFUNDREQUEST captures enum value "REFUND_REQUEST"
	SupportpbTicketCategoryREFUNDREQUEST SupportpbTicketCategory = "REFUND_REQUEST"

	// SupportpbTicketCategoryORDERISSUE captures enum value "ORDER_ISSUE"
	SupportpbTicketCategoryORDERISSUE SupportpbTicketCategory = "ORDER_ISSUE"

	// SupportpbTicketCategorySHIPPINGISSUE captures enum value "SHIPPING_ISSUE"
	SupportpbTicketCategorySHIPPINGISSUE SupportpbTicketCategory = "SHIPPING_ISSUE"
)

// for schema
var supportpbTicketCategoryEnum []interface{}

func init() {
	var res []SupportpbTicketCategory
	if err := json.Unmarshal([]byte(`["GENERAL_INQUIRY","TECHNICAL_ISSUE","BILLING_ISSUE","ACCOUNT_ISSUE","PRODUCT_QUESTION","FEATURE_REQUEST","COMPLAINT","REFUND_REQUEST","ORDER_ISSUE","SHIPPING_ISSUE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		supportpbTicketCategoryEnum = append(supportpbTicketCategoryEnum, v)
	}
}

func (m SupportpbTicketCategory) validateSupportpbTicketCategoryEnum(path, location string, value SupportpbTicketCategory) error {
	if err := validate.EnumCase(path, location, value, supportpbTicketCategoryEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this supportpb ticket category
func (m SupportpbTicketCategory) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateSupportpbTicketCategoryEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this supportpb ticket category based on context it is used
func (m SupportpbTicketCategory) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
