// Code generated by go-swagger; DO NOT EDIT.

package post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"middleman/posts/postsclient/models"
)

// AddPostThumbnailReader is a Reader for the AddPostThumbnail structure.
type AddPostThumbnailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddPostThumbnailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddPostThumbnailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAddPostThumbnailDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAddPostThumbnailOK creates a AddPostThumbnailOK with default headers values
func NewAddPostThumbnailOK() *AddPostThumbnailOK {
	return &AddPostThumbnailOK{}
}

/*
AddPostThumbnailOK describes a response with status code 200, with default header values.

A successful response.
*/
type AddPostThumbnailOK struct {
	Payload *models.PostspbAddPostThumbnailResponse
}

// IsSuccess returns true when this add post thumbnail o k response has a 2xx status code
func (o *AddPostThumbnailOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this add post thumbnail o k response has a 3xx status code
func (o *AddPostThumbnailOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add post thumbnail o k response has a 4xx status code
func (o *AddPostThumbnailOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this add post thumbnail o k response has a 5xx status code
func (o *AddPostThumbnailOK) IsServerError() bool {
	return false
}

// IsCode returns true when this add post thumbnail o k response a status code equal to that given
func (o *AddPostThumbnailOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the add post thumbnail o k response
func (o *AddPostThumbnailOK) Code() int {
	return 200
}

func (o *AddPostThumbnailOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/posts/{postId}/thumbnail/add][%d] addPostThumbnailOK %s", 200, payload)
}

func (o *AddPostThumbnailOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/posts/{postId}/thumbnail/add][%d] addPostThumbnailOK %s", 200, payload)
}

func (o *AddPostThumbnailOK) GetPayload() *models.PostspbAddPostThumbnailResponse {
	return o.Payload
}

func (o *AddPostThumbnailOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PostspbAddPostThumbnailResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddPostThumbnailDefault creates a AddPostThumbnailDefault with default headers values
func NewAddPostThumbnailDefault(code int) *AddPostThumbnailDefault {
	return &AddPostThumbnailDefault{
		_statusCode: code,
	}
}

/*
AddPostThumbnailDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type AddPostThumbnailDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this add post thumbnail default response has a 2xx status code
func (o *AddPostThumbnailDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this add post thumbnail default response has a 3xx status code
func (o *AddPostThumbnailDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this add post thumbnail default response has a 4xx status code
func (o *AddPostThumbnailDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this add post thumbnail default response has a 5xx status code
func (o *AddPostThumbnailDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this add post thumbnail default response a status code equal to that given
func (o *AddPostThumbnailDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the add post thumbnail default response
func (o *AddPostThumbnailDefault) Code() int {
	return o._statusCode
}

func (o *AddPostThumbnailDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/posts/{postId}/thumbnail/add][%d] addPostThumbnail default %s", o._statusCode, payload)
}

func (o *AddPostThumbnailDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/posts/{postId}/thumbnail/add][%d] addPostThumbnail default %s", o._statusCode, payload)
}

func (o *AddPostThumbnailDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *AddPostThumbnailDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
