// Code generated by go-swagger; DO NOT EDIT.

package post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPostParams creates a new GetPostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPostParams() *GetPostParams {
	return &GetPostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPostParamsWithTimeout creates a new GetPostParams object
// with the ability to set a timeout on a request.
func NewGetPostParamsWithTimeout(timeout time.Duration) *GetPostParams {
	return &GetPostParams{
		timeout: timeout,
	}
}

// NewGetPostParamsWithContext creates a new GetPostParams object
// with the ability to set a context for a request.
func NewGetPostParamsWithContext(ctx context.Context) *GetPostParams {
	return &GetPostParams{
		Context: ctx,
	}
}

// NewGetPostParamsWithHTTPClient creates a new GetPostParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPostParamsWithHTTPClient(client *http.Client) *GetPostParams {
	return &GetPostParams{
		HTTPClient: client,
	}
}

/*
GetPostParams contains all the parameters to send to the API endpoint

	for the get post operation.

	Typically these are written to a http.Request.
*/
type GetPostParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPostParams) WithDefaults() *GetPostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get post params
func (o *GetPostParams) WithTimeout(timeout time.Duration) *GetPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get post params
func (o *GetPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get post params
func (o *GetPostParams) WithContext(ctx context.Context) *GetPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get post params
func (o *GetPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get post params
func (o *GetPostParams) WithHTTPClient(client *http.Client) *GetPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get post params
func (o *GetPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get post params
func (o *GetPostParams) WithID(id string) *GetPostParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get post params
func (o *GetPostParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
