// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MessagespbSendMessageResponse Response message after sending a new message.
//
// swagger:model messagespbSendMessageResponse
type MessagespbSendMessageResponse struct {

	// Unique identifier of the sent message.
	ID string `json:"id,omitempty"`

	// Timestamp when the message was sent.
	// Format: date-time
	SentAt strfmt.DateTime `json:"sentAt,omitempty"`
}

// Validate validates this messagespb send message response
func (m *MessagespbSendMessageResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSentAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MessagespbSendMessageResponse) validateSentAt(formats strfmt.Registry) error {
	if swag.IsZero(m.SentAt) { // not required
		return nil
	}

	if err := validate.FormatOf("sentAt", "body", "date-time", m.SentAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this messagespb send message response based on context it is used
func (m *MessagespbSendMessageResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MessagespbSendMessageResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MessagespbSendMessageResponse) UnmarshalBinary(b []byte) error {
	var res MessagespbSendMessageResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
