// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: merchantpb/messages.proto

package merchantpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_merchantpb_messages_proto protoreflect.FileDescriptor

const file_merchantpb_messages_proto_rawDesc = "" +
	"\n" +
	"\x19merchantpb/messages.proto\x12\n" +
	"merchantpbB\x91\x01\n" +
	"\x0ecom.merchantpbB\rMessagesProtoP\x01Z(middleman/merchant/merchantpb/merchantpb\xa2\x02\x03MXX\xaa\x02\n" +
	"Merchantpb\xca\x02\n" +
	"Merchantpb\xe2\x02\x16Merchantpb\\GPBMetadata\xea\x02\n" +
	"Merchantpbb\x06proto3"

var file_merchantpb_messages_proto_goTypes = []any{}
var file_merchantpb_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_merchantpb_messages_proto_init() }
func file_merchantpb_messages_proto_init() {
	if File_merchantpb_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchantpb_messages_proto_rawDesc), len(file_merchantpb_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_merchantpb_messages_proto_goTypes,
		DependencyIndexes: file_merchantpb_messages_proto_depIdxs,
	}.Build()
	File_merchantpb_messages_proto = out.File
	file_merchantpb_messages_proto_goTypes = nil
	file_merchantpb_messages_proto_depIdxs = nil
}
