// Code generated by mockery v2.53.4. DO NOT EDIT.

package merchantpb

import mock "github.com/stretchr/testify/mock"

// MockUnsafeMerchantServiceServer is an autogenerated mock type for the UnsafeMerchantServiceServer type
type MockUnsafeMerchantServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedMerchantServiceServer provides a mock function with no fields
func (_m *MockUnsafeMerchantServiceServer) mustEmbedUnimplementedMerchantServiceServer() {
	_m.Called()
}

// NewMockUnsafeMerchantServiceServer creates a new instance of MockUnsafeMerchantServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeMerchantServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeMerchantServiceServer {
	mock := &MockUnsafeMerchantServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
