apiVersion: 1

datasources:
  - name: Prometheus
    uid: webstore-metrics
    type: prometheus
    url: http://prometheus:9090
    editable: true
    isDefault: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - datasourceUid: jaeger
          name: trace_id

  - name: Jaeger
    uid: jaeger
    type: jaeger
    url: http://jaeger:16686
    access: proxy
    editable: true
    jsonData:
      nodeGraph:
        enabled: true
