// Code generated by go-swagger; DO NOT EDIT.

package subscription

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"middleman/newsletters/newslettersclient/models"
)

// UnsubscribeNewsletterReader is a Reader for the UnsubscribeNewsletter structure.
type UnsubscribeNewsletterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UnsubscribeNewsletterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUnsubscribeNewsletterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewUnsubscribeNewsletterDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUnsubscribeNewsletterOK creates a UnsubscribeNewsletterOK with default headers values
func NewUnsubscribeNewsletterOK() *UnsubscribeNewsletterOK {
	return &UnsubscribeNewsletterOK{}
}

/*
UnsubscribeNewsletterOK describes a response with status code 200, with default header values.

A successful response.
*/
type UnsubscribeNewsletterOK struct {
	Payload interface{}
}

// IsSuccess returns true when this unsubscribe newsletter o k response has a 2xx status code
func (o *UnsubscribeNewsletterOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this unsubscribe newsletter o k response has a 3xx status code
func (o *UnsubscribeNewsletterOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this unsubscribe newsletter o k response has a 4xx status code
func (o *UnsubscribeNewsletterOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this unsubscribe newsletter o k response has a 5xx status code
func (o *UnsubscribeNewsletterOK) IsServerError() bool {
	return false
}

// IsCode returns true when this unsubscribe newsletter o k response a status code equal to that given
func (o *UnsubscribeNewsletterOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the unsubscribe newsletter o k response
func (o *UnsubscribeNewsletterOK) Code() int {
	return 200
}

func (o *UnsubscribeNewsletterOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/newsletters/subscriptions/{subscriptionId}][%d] unsubscribeNewsletterOK %s", 200, payload)
}

func (o *UnsubscribeNewsletterOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/newsletters/subscriptions/{subscriptionId}][%d] unsubscribeNewsletterOK %s", 200, payload)
}

func (o *UnsubscribeNewsletterOK) GetPayload() interface{} {
	return o.Payload
}

func (o *UnsubscribeNewsletterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUnsubscribeNewsletterDefault creates a UnsubscribeNewsletterDefault with default headers values
func NewUnsubscribeNewsletterDefault(code int) *UnsubscribeNewsletterDefault {
	return &UnsubscribeNewsletterDefault{
		_statusCode: code,
	}
}

/*
UnsubscribeNewsletterDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type UnsubscribeNewsletterDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this unsubscribe newsletter default response has a 2xx status code
func (o *UnsubscribeNewsletterDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this unsubscribe newsletter default response has a 3xx status code
func (o *UnsubscribeNewsletterDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this unsubscribe newsletter default response has a 4xx status code
func (o *UnsubscribeNewsletterDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this unsubscribe newsletter default response has a 5xx status code
func (o *UnsubscribeNewsletterDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this unsubscribe newsletter default response a status code equal to that given
func (o *UnsubscribeNewsletterDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the unsubscribe newsletter default response
func (o *UnsubscribeNewsletterDefault) Code() int {
	return o._statusCode
}

func (o *UnsubscribeNewsletterDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/newsletters/subscriptions/{subscriptionId}][%d] unsubscribeNewsletter default %s", o._statusCode, payload)
}

func (o *UnsubscribeNewsletterDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/newsletters/subscriptions/{subscriptionId}][%d] unsubscribeNewsletter default %s", o._statusCode, payload)
}

func (o *UnsubscribeNewsletterDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *UnsubscribeNewsletterDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
