// Code generated by go-swagger; DO NOT EDIT.

package connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"middleman/erp/erpclient/models"
)

// NewRegisterConnectorParams creates a new RegisterConnectorParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRegisterConnectorParams() *RegisterConnectorParams {
	return &RegisterConnectorParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRegisterConnectorParamsWithTimeout creates a new RegisterConnectorParams object
// with the ability to set a timeout on a request.
func NewRegisterConnectorParamsWithTimeout(timeout time.Duration) *RegisterConnectorParams {
	return &RegisterConnectorParams{
		timeout: timeout,
	}
}

// NewRegisterConnectorParamsWithContext creates a new RegisterConnectorParams object
// with the ability to set a context for a request.
func NewRegisterConnectorParamsWithContext(ctx context.Context) *RegisterConnectorParams {
	return &RegisterConnectorParams{
		Context: ctx,
	}
}

// NewRegisterConnectorParamsWithHTTPClient creates a new RegisterConnectorParams object
// with the ability to set a custom HTTPClient for a request.
func NewRegisterConnectorParamsWithHTTPClient(client *http.Client) *RegisterConnectorParams {
	return &RegisterConnectorParams{
		HTTPClient: client,
	}
}

/*
RegisterConnectorParams contains all the parameters to send to the API endpoint

	for the register connector operation.

	Typically these are written to a http.Request.
*/
type RegisterConnectorParams struct {

	// Body.
	Body *models.ErppbRegisterConnectorRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the register connector params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RegisterConnectorParams) WithDefaults() *RegisterConnectorParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the register connector params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RegisterConnectorParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the register connector params
func (o *RegisterConnectorParams) WithTimeout(timeout time.Duration) *RegisterConnectorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the register connector params
func (o *RegisterConnectorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the register connector params
func (o *RegisterConnectorParams) WithContext(ctx context.Context) *RegisterConnectorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the register connector params
func (o *RegisterConnectorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the register connector params
func (o *RegisterConnectorParams) WithHTTPClient(client *http.Client) *RegisterConnectorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the register connector params
func (o *RegisterConnectorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the register connector params
func (o *RegisterConnectorParams) WithBody(body *models.ErppbRegisterConnectorRequest) *RegisterConnectorParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the register connector params
func (o *RegisterConnectorParams) SetBody(body *models.ErppbRegisterConnectorRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RegisterConnectorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
