// Code generated by go-swagger; DO NOT EDIT.

package product

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"middleman/products/productsclient/models"
)

// GetProductsReader is a Reader for the GetProducts structure.
type GetProductsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProductsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProductsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetProductsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetProductsOK creates a GetProductsOK with default headers values
func NewGetProductsOK() *GetProductsOK {
	return &GetProductsOK{}
}

/*
GetProductsOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetProductsOK struct {
	Payload *models.ProductspbGetProductsResponse
}

// IsSuccess returns true when this get products o k response has a 2xx status code
func (o *GetProductsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get products o k response has a 3xx status code
func (o *GetProductsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get products o k response has a 4xx status code
func (o *GetProductsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get products o k response has a 5xx status code
func (o *GetProductsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get products o k response a status code equal to that given
func (o *GetProductsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get products o k response
func (o *GetProductsOK) Code() int {
	return 200
}

func (o *GetProductsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/products][%d] getProductsOK %s", 200, payload)
}

func (o *GetProductsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/products][%d] getProductsOK %s", 200, payload)
}

func (o *GetProductsOK) GetPayload() *models.ProductspbGetProductsResponse {
	return o.Payload
}

func (o *GetProductsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProductspbGetProductsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProductsDefault creates a GetProductsDefault with default headers values
func NewGetProductsDefault(code int) *GetProductsDefault {
	return &GetProductsDefault{
		_statusCode: code,
	}
}

/*
GetProductsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetProductsDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this get products default response has a 2xx status code
func (o *GetProductsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get products default response has a 3xx status code
func (o *GetProductsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get products default response has a 4xx status code
func (o *GetProductsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get products default response has a 5xx status code
func (o *GetProductsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get products default response a status code equal to that given
func (o *GetProductsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get products default response
func (o *GetProductsDefault) Code() int {
	return o._statusCode
}

func (o *GetProductsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/products][%d] getProducts default %s", o._statusCode, payload)
}

func (o *GetProductsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/products][%d] getProducts default %s", o._statusCode, payload)
}

func (o *GetProductsDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *GetProductsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
