// Code generated by go-swagger; DO NOT EDIT.

package products_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"middleman/products/productsclient/models"
)

// NewProductsServiceUpdateProductParams creates a new ProductsServiceUpdateProductParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewProductsServiceUpdateProductParams() *ProductsServiceUpdateProductParams {
	return &ProductsServiceUpdateProductParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewProductsServiceUpdateProductParamsWithTimeout creates a new ProductsServiceUpdateProductParams object
// with the ability to set a timeout on a request.
func NewProductsServiceUpdateProductParamsWithTimeout(timeout time.Duration) *ProductsServiceUpdateProductParams {
	return &ProductsServiceUpdateProductParams{
		timeout: timeout,
	}
}

// NewProductsServiceUpdateProductParamsWithContext creates a new ProductsServiceUpdateProductParams object
// with the ability to set a context for a request.
func NewProductsServiceUpdateProductParamsWithContext(ctx context.Context) *ProductsServiceUpdateProductParams {
	return &ProductsServiceUpdateProductParams{
		Context: ctx,
	}
}

// NewProductsServiceUpdateProductParamsWithHTTPClient creates a new ProductsServiceUpdateProductParams object
// with the ability to set a custom HTTPClient for a request.
func NewProductsServiceUpdateProductParamsWithHTTPClient(client *http.Client) *ProductsServiceUpdateProductParams {
	return &ProductsServiceUpdateProductParams{
		HTTPClient: client,
	}
}

/*
ProductsServiceUpdateProductParams contains all the parameters to send to the API endpoint

	for the products service update product operation.

	Typically these are written to a http.Request.
*/
type ProductsServiceUpdateProductParams struct {

	// Body.
	Body *models.ProductsServiceUpdateProductBody

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the products service update product params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProductsServiceUpdateProductParams) WithDefaults() *ProductsServiceUpdateProductParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the products service update product params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProductsServiceUpdateProductParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the products service update product params
func (o *ProductsServiceUpdateProductParams) WithTimeout(timeout time.Duration) *ProductsServiceUpdateProductParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the products service update product params
func (o *ProductsServiceUpdateProductParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the products service update product params
func (o *ProductsServiceUpdateProductParams) WithContext(ctx context.Context) *ProductsServiceUpdateProductParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the products service update product params
func (o *ProductsServiceUpdateProductParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the products service update product params
func (o *ProductsServiceUpdateProductParams) WithHTTPClient(client *http.Client) *ProductsServiceUpdateProductParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the products service update product params
func (o *ProductsServiceUpdateProductParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the products service update product params
func (o *ProductsServiceUpdateProductParams) WithBody(body *models.ProductsServiceUpdateProductBody) *ProductsServiceUpdateProductParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the products service update product params
func (o *ProductsServiceUpdateProductParams) SetBody(body *models.ProductsServiceUpdateProductBody) {
	o.Body = body
}

// WithID adds the id to the products service update product params
func (o *ProductsServiceUpdateProductParams) WithID(id string) *ProductsServiceUpdateProductParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the products service update product params
func (o *ProductsServiceUpdateProductParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ProductsServiceUpdateProductParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
