// Code generated by go-swagger; DO NOT EDIT.

package conversation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetUserConversationsParams creates a new GetUserConversationsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUserConversationsParams() *GetUserConversationsParams {
	return &GetUserConversationsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserConversationsParamsWithTimeout creates a new GetUserConversationsParams object
// with the ability to set a timeout on a request.
func NewGetUserConversationsParamsWithTimeout(timeout time.Duration) *GetUserConversationsParams {
	return &GetUserConversationsParams{
		timeout: timeout,
	}
}

// NewGetUserConversationsParamsWithContext creates a new GetUserConversationsParams object
// with the ability to set a context for a request.
func NewGetUserConversationsParamsWithContext(ctx context.Context) *GetUserConversationsParams {
	return &GetUserConversationsParams{
		Context: ctx,
	}
}

// NewGetUserConversationsParamsWithHTTPClient creates a new GetUserConversationsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUserConversationsParamsWithHTTPClient(client *http.Client) *GetUserConversationsParams {
	return &GetUserConversationsParams{
		HTTPClient: client,
	}
}

/*
GetUserConversationsParams contains all the parameters to send to the API endpoint

	for the get user conversations operation.

	Typically these are written to a http.Request.
*/
type GetUserConversationsParams struct {

	// ActiveOnly.
	ActiveOnly *bool

	// Limit.
	//
	// Format: int32
	Limit *int32

	// Page.
	//
	// Format: int32
	Page *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get user conversations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUserConversationsParams) WithDefaults() *GetUserConversationsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get user conversations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUserConversationsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get user conversations params
func (o *GetUserConversationsParams) WithTimeout(timeout time.Duration) *GetUserConversationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get user conversations params
func (o *GetUserConversationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get user conversations params
func (o *GetUserConversationsParams) WithContext(ctx context.Context) *GetUserConversationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get user conversations params
func (o *GetUserConversationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get user conversations params
func (o *GetUserConversationsParams) WithHTTPClient(client *http.Client) *GetUserConversationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get user conversations params
func (o *GetUserConversationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithActiveOnly adds the activeOnly to the get user conversations params
func (o *GetUserConversationsParams) WithActiveOnly(activeOnly *bool) *GetUserConversationsParams {
	o.SetActiveOnly(activeOnly)
	return o
}

// SetActiveOnly adds the activeOnly to the get user conversations params
func (o *GetUserConversationsParams) SetActiveOnly(activeOnly *bool) {
	o.ActiveOnly = activeOnly
}

// WithLimit adds the limit to the get user conversations params
func (o *GetUserConversationsParams) WithLimit(limit *int32) *GetUserConversationsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get user conversations params
func (o *GetUserConversationsParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithPage adds the page to the get user conversations params
func (o *GetUserConversationsParams) WithPage(page *int32) *GetUserConversationsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get user conversations params
func (o *GetUserConversationsParams) SetPage(page *int32) {
	o.Page = page
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserConversationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ActiveOnly != nil {

		// query param activeOnly
		var qrActiveOnly bool

		if o.ActiveOnly != nil {
			qrActiveOnly = *o.ActiveOnly
		}
		qActiveOnly := swag.FormatBool(qrActiveOnly)
		if qActiveOnly != "" {

			if err := r.SetQueryParam("activeOnly", qActiveOnly); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int32

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Page != nil {

		// query param page
		var qrPage int32

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt32(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
