// Code generated by mockery v2.53.4. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEmailRepository is an autogenerated mock type for the EmailRepository type
type MockEmailRepository struct {
	mock.Mock
}

// Load provides a mock function with given fields: ctx, id
func (_m *MockEmailRepository) Load(ctx context.Context, id string) (*Email, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *Email
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*Email, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *Email); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Email)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, mailer
func (_m *MockEmailRepository) Save(ctx context.Context, mailer *Email) error {
	ret := _m.Called(ctx, mailer)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Email) error); ok {
		r0 = rf(ctx, mailer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockEmailRepository creates a new instance of MockEmailRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailRepository {
	mock := &MockEmailRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
