// Code generated by go-swagger; DO NOT EDIT.

package edition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"middleman/newsletters/newslettersclient/models"
)

// NewScheduleEditionParams creates a new ScheduleEditionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewScheduleEditionParams() *ScheduleEditionParams {
	return &ScheduleEditionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewScheduleEditionParamsWithTimeout creates a new ScheduleEditionParams object
// with the ability to set a timeout on a request.
func NewScheduleEditionParamsWithTimeout(timeout time.Duration) *ScheduleEditionParams {
	return &ScheduleEditionParams{
		timeout: timeout,
	}
}

// NewScheduleEditionParamsWithContext creates a new ScheduleEditionParams object
// with the ability to set a context for a request.
func NewScheduleEditionParamsWithContext(ctx context.Context) *ScheduleEditionParams {
	return &ScheduleEditionParams{
		Context: ctx,
	}
}

// NewScheduleEditionParamsWithHTTPClient creates a new ScheduleEditionParams object
// with the ability to set a custom HTTPClient for a request.
func NewScheduleEditionParamsWithHTTPClient(client *http.Client) *ScheduleEditionParams {
	return &ScheduleEditionParams{
		HTTPClient: client,
	}
}

/*
ScheduleEditionParams contains all the parameters to send to the API endpoint

	for the schedule edition operation.

	Typically these are written to a http.Request.
*/
type ScheduleEditionParams struct {

	// Body.
	Body *models.NewslettersServiceScheduleEditionBody

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the schedule edition params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ScheduleEditionParams) WithDefaults() *ScheduleEditionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the schedule edition params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ScheduleEditionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the schedule edition params
func (o *ScheduleEditionParams) WithTimeout(timeout time.Duration) *ScheduleEditionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the schedule edition params
func (o *ScheduleEditionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the schedule edition params
func (o *ScheduleEditionParams) WithContext(ctx context.Context) *ScheduleEditionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the schedule edition params
func (o *ScheduleEditionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the schedule edition params
func (o *ScheduleEditionParams) WithHTTPClient(client *http.Client) *ScheduleEditionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the schedule edition params
func (o *ScheduleEditionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the schedule edition params
func (o *ScheduleEditionParams) WithBody(body *models.NewslettersServiceScheduleEditionBody) *ScheduleEditionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the schedule edition params
func (o *ScheduleEditionParams) SetBody(body *models.NewslettersServiceScheduleEditionBody) {
	o.Body = body
}

// WithID adds the id to the schedule edition params
func (o *ScheduleEditionParams) WithID(id string) *ScheduleEditionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the schedule edition params
func (o *ScheduleEditionParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ScheduleEditionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
