// Code generated by go-swagger; DO NOT EDIT.

package ordering_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"middleman/ordering/orderingclient/models"
)

// OrderingServiceRejectOrderReader is a Reader for the OrderingServiceRejectOrder structure.
type OrderingServiceRejectOrderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrderingServiceRejectOrderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOrderingServiceRejectOrderOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewOrderingServiceRejectOrderDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewOrderingServiceRejectOrderOK creates a OrderingServiceRejectOrderOK with default headers values
func NewOrderingServiceRejectOrderOK() *OrderingServiceRejectOrderOK {
	return &OrderingServiceRejectOrderOK{}
}

/*
OrderingServiceRejectOrderOK describes a response with status code 200, with default header values.

A successful response.
*/
type OrderingServiceRejectOrderOK struct {
	Payload *models.OrderingpbRejectOrderResponse
}

// IsSuccess returns true when this ordering service reject order o k response has a 2xx status code
func (o *OrderingServiceRejectOrderOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ordering service reject order o k response has a 3xx status code
func (o *OrderingServiceRejectOrderOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ordering service reject order o k response has a 4xx status code
func (o *OrderingServiceRejectOrderOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this ordering service reject order o k response has a 5xx status code
func (o *OrderingServiceRejectOrderOK) IsServerError() bool {
	return false
}

// IsCode returns true when this ordering service reject order o k response a status code equal to that given
func (o *OrderingServiceRejectOrderOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the ordering service reject order o k response
func (o *OrderingServiceRejectOrderOK) Code() int {
	return 200
}

func (o *OrderingServiceRejectOrderOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/ordering/{id}/reject][%d] orderingServiceRejectOrderOK %s", 200, payload)
}

func (o *OrderingServiceRejectOrderOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/ordering/{id}/reject][%d] orderingServiceRejectOrderOK %s", 200, payload)
}

func (o *OrderingServiceRejectOrderOK) GetPayload() *models.OrderingpbRejectOrderResponse {
	return o.Payload
}

func (o *OrderingServiceRejectOrderOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OrderingpbRejectOrderResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOrderingServiceRejectOrderDefault creates a OrderingServiceRejectOrderDefault with default headers values
func NewOrderingServiceRejectOrderDefault(code int) *OrderingServiceRejectOrderDefault {
	return &OrderingServiceRejectOrderDefault{
		_statusCode: code,
	}
}

/*
OrderingServiceRejectOrderDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type OrderingServiceRejectOrderDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this ordering service reject order default response has a 2xx status code
func (o *OrderingServiceRejectOrderDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this ordering service reject order default response has a 3xx status code
func (o *OrderingServiceRejectOrderDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this ordering service reject order default response has a 4xx status code
func (o *OrderingServiceRejectOrderDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this ordering service reject order default response has a 5xx status code
func (o *OrderingServiceRejectOrderDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this ordering service reject order default response a status code equal to that given
func (o *OrderingServiceRejectOrderDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the ordering service reject order default response
func (o *OrderingServiceRejectOrderDefault) Code() int {
	return o._statusCode
}

func (o *OrderingServiceRejectOrderDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/ordering/{id}/reject][%d] OrderingService_RejectOrder default %s", o._statusCode, payload)
}

func (o *OrderingServiceRejectOrderDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/ordering/{id}/reject][%d] OrderingService_RejectOrder default %s", o._statusCode, payload)
}

func (o *OrderingServiceRejectOrderDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *OrderingServiceRejectOrderDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
