// Code generated by go-swagger; DO NOT EDIT.

package item_comment_count

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"middleman/comments/commentsclient/models"
)

// GetMostCommentedByCategoryReader is a Reader for the GetMostCommentedByCategory structure.
type GetMostCommentedByCategoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMostCommentedByCategoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMostCommentedByCategoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetMostCommentedByCategoryDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetMostCommentedByCategoryOK creates a GetMostCommentedByCategoryOK with default headers values
func NewGetMostCommentedByCategoryOK() *GetMostCommentedByCategoryOK {
	return &GetMostCommentedByCategoryOK{}
}

/*
GetMostCommentedByCategoryOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetMostCommentedByCategoryOK struct {
	Payload *models.CommentspbGetMostCommentedByCategoryResponse
}

// IsSuccess returns true when this get most commented by category o k response has a 2xx status code
func (o *GetMostCommentedByCategoryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get most commented by category o k response has a 3xx status code
func (o *GetMostCommentedByCategoryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get most commented by category o k response has a 4xx status code
func (o *GetMostCommentedByCategoryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get most commented by category o k response has a 5xx status code
func (o *GetMostCommentedByCategoryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get most commented by category o k response a status code equal to that given
func (o *GetMostCommentedByCategoryOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get most commented by category o k response
func (o *GetMostCommentedByCategoryOK) Code() int {
	return 200
}

func (o *GetMostCommentedByCategoryOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/comments/most/{categoryId}][%d] getMostCommentedByCategoryOK %s", 200, payload)
}

func (o *GetMostCommentedByCategoryOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/comments/most/{categoryId}][%d] getMostCommentedByCategoryOK %s", 200, payload)
}

func (o *GetMostCommentedByCategoryOK) GetPayload() *models.CommentspbGetMostCommentedByCategoryResponse {
	return o.Payload
}

func (o *GetMostCommentedByCategoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommentspbGetMostCommentedByCategoryResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMostCommentedByCategoryDefault creates a GetMostCommentedByCategoryDefault with default headers values
func NewGetMostCommentedByCategoryDefault(code int) *GetMostCommentedByCategoryDefault {
	return &GetMostCommentedByCategoryDefault{
		_statusCode: code,
	}
}

/*
GetMostCommentedByCategoryDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetMostCommentedByCategoryDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this get most commented by category default response has a 2xx status code
func (o *GetMostCommentedByCategoryDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get most commented by category default response has a 3xx status code
func (o *GetMostCommentedByCategoryDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get most commented by category default response has a 4xx status code
func (o *GetMostCommentedByCategoryDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get most commented by category default response has a 5xx status code
func (o *GetMostCommentedByCategoryDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get most commented by category default response a status code equal to that given
func (o *GetMostCommentedByCategoryDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get most commented by category default response
func (o *GetMostCommentedByCategoryDefault) Code() int {
	return o._statusCode
}

func (o *GetMostCommentedByCategoryDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/comments/most/{categoryId}][%d] getMostCommentedByCategory default %s", o._statusCode, payload)
}

func (o *GetMostCommentedByCategoryDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/comments/most/{categoryId}][%d] getMostCommentedByCategory default %s", o._statusCode, payload)
}

func (o *GetMostCommentedByCategoryDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *GetMostCommentedByCategoryDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
