// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AssistantspbUpdateConversationContextRequest Update Conversation Context
//
// swagger:model assistantspbUpdateConversationContextRequest
type AssistantspbUpdateConversationContextRequest struct {

	// context
	Context map[string]string `json:"context,omitempty"`

	// conversation Id
	ConversationID string `json:"conversationId,omitempty"`
}

// Validate validates this assistantspb update conversation context request
func (m *AssistantspbUpdateConversationContextRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this assistantspb update conversation context request based on context it is used
func (m *AssistantspbUpdateConversationContextRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AssistantspbUpdateConversationContextRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AssistantspbUpdateConversationContextRequest) UnmarshalBinary(b []byte) error {
	var res AssistantspbUpdateConversationContextRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
